package main

// videoEntry is one real YouTube video (id + its title) from a language's Go
// course playlist. Generated from the playlists the user supplied (ru/uz/ja)
// plus Matt Holiday's "Go Class" for en. Used to seed per-language videos.
type videoEntry struct {
	ID    string
	Title string
}

// videoPlaylists holds the per-language Go course videos in playlist order.
var videoPlaylists = map[string][]videoEntry{
	"ru": {
		{"eQPfHdiz_KI", "Изучаем Go. Урок №1. Установка Go, выбор IDE, первая программа #golang"},
		{"UihSL2jV9dI", "Изучаем Go. Урок №2. Переменные, константы. Типы. Области видимости. Преобразование типов #golang"},
		{"8pKpMtWCOPA", "Изучаем Go. Урок №3. Функции (основы) #golang"},
		{"JuDkZuO6KhI", "Изучаем Go. Урок №4. Функции (advanced) #golang"},
		{"HUt2CCW8qIM", "Изучаем Go. Урок №5. Условный оператор (if/else). Логические операторы #golang"},
		{"qTRS85vKzuE", "Learning Go. Lesson #6. Loops (for, for as while). Increment. Decrement #golang"},
		{"9ZpQQoIrpOc", "Изучаем Go. Урок №7. Циклы (2). Continue. Break #golang"},
		{"PpGGHseY1is", "Изучаем Go. Урок №8. Switch .. case #golang"},
		{"q4NHCydLfpQ", "Изучаем Go. Урок №9. Указатели (pointers) #golang"},
		{"HtP79INU6PM", "Learning Go. Lesson #10. Pointers (2). Usecases #golang"},
		{"3SYe5TepPwI", "Изучаем Go. Урок №11. Кастомные типы. Структуры(1) #golang"},
		{"SQrjgZR2u1s", "Learning Go. Lesson #12. Methods #golang"},
		{"Et3uJTXYNuI", "Изучаем Go. Урок №13. Интерфейсы #golang"},
		{"Mi2mqnGm1h8", "Изучаем Go. Урок №14. Структуры (2) Встраивание типов (Embedding) #golang"},
		{"-fhgodk2JLQ", "Изучаем Go. Урок №15. Массивы (arrays). Слайсы (slices)(1) #golang"},
		{"ecetBuEZ8oc", "Learning Go. Lesson #16. Slices (2) #golang"},
		{"ryHn-zHj7E8", "Изучаем Go. Урок №17. Слайсы (slices)(3) #golang"},
		{"DTJ9Q-k0CEc", "Изучаем Go. Урок №18. Мапы (maps) #golang"},
		{"wbK_GtZNox8", "Изучаем Go. Урок №19. Concurrency (1). Goroutines. Defer. Panic/Recover #golang"},
		{"RaMQrV7x-1k", "Изучаем Go. Урок №20. Concurrency (2). WaitGroup. Data Race. Mutex/RWMutex #golang"},
		{"ngEj0ZwQEn0", "Изучаем Go. Урок №21. Concurrency (3). Каналы (channels). Deadlock. #golang"},
		{"kSfR5LWKUrM", "Learning Go. Lesson #22. Concurrency (4). Select. Graceful shutdown. #golang"},
		{"qDgs2FJakVQ", "Learning Go. Lesson #23. Concurrency (5). Context #golang"},
		{"jKDhxqclywg", "Изучаем Go. Урок №24. Concurrency (6). ErrGroup. Канал как Mutex. Промисы на каналах #golang"},
		{"VFKl0BquQgA", "Learning Go. Lesson #25. Concurrency (7). Atomic #golang"},
		{"0e_mr6jsDxI", "Изучаем Go. Урок №26. Дженерики(generics) #golang"},
		{"Ms4k7O64H0E", "Изучаем Go. Урок №27. Пакеты (Packages) #golang"},
		{"RRy286VuOkE", "Изучаем Go. Урок №28. Модули (Modules) #golang"},
		{"nIWt-J0gyKI", "Изучаем Go. Урок №29. Работа с файлами(1). io.Reader и io.Writer. Пакет os #golang"},
		{"IT8QcmgjJVk", "Изучаем Go. Урок №30. Работа с файлами(2). Потоки ввода, вывода, ошибок. Аргументы запуска программ"},
		{"5G_cgAe9lUs", "Как учить Go в 2024. Обсуждаем Roadmap"},
		{"isF-lqhoX-w", "Изучаем Go. Урок №31. Работа с файлами(3). io.WriterTo, io.ReaderFrom, io.Copy, bufio.Writer"},
		{"jYcClWSD4Yc", "Полный гайд по JSON в Go"},
	},
	"en": {
		{"iDQAZEJK8lI", "Go Class: 00 Intro and Why Use Go?"},
		{"A9HfEhvpOEY", "Go Class: 01 Hello world!"},
		{"-EYNVEv-snE", "Go Class: 02 Simple Example"},
		{"NNLpEPb2ddE", "Go Class: 03 Basic Types"},
		{"nxWqANttAdA", "Go Class: 04 Strings"},
		{"T0Xymg0_aSU", "Go Class: 05 Arrays, Slices, and Maps"},
		{"qpHLhmoV3BY", "Go Class: 06 Control Statements; Declarations & Types"},
		{"dqEtGT-dxoY", "Go Class: 07 Formatted & File I/O"},
		{"wj0hUjRHkPs", "Go Class: 08 Functions, Parameters & Defer"},
		{"US3TGA-Dpqo", "Go Class: 09 Closures"},
		{"pHl9r3B2DFI", "Go Class: 10 Slices in Detail"},
		{"CR4OYGxaie8", "Go Class: 11 Homework #2"},
		{"0m6iFd9N_CY", "Go Class: 12 Structs, Struct tags & JSON"},
		{"904pyovPvXM", "Go Class: 14 Reference & Value Semantics"},
		{"Q-uy0FS6RwU", "Go Class: 15 Networking with HTTP"},
		{"mFB6_sOiggI", "Go Class: 16 Homework #3"},
		{"jexEpE7Yv2A", "Go Class: 17 Go does OOP"},
		{"W3ZWbhQF6wg", "Go Class: 18 Methods and Interfaces"},
		{"0X6AcnwocbM", "Go Class: 19 Composition"},
		{"AXCIEiebVfI", "Go Class: 20 Interfaces & Methods in Detail"},
		{"YUaruvHkXio", "Go Class: 21 Homework #4"},
		{"A3R-4ZYBqvE", "Go Class: 22 What is Concurrency?"},
		{"zJd7Dvg3XCk", "Go Class: 23 CSP, Goroutines, and Channels"},
		{"tG7gII0Ax0Q", "Go Class: 24 Select"},
		{"0x_oUlxzw5A", "Go Class: 25 Context"},
		{"fCkxKGd6CVQ", "Go Class: 26 Channels in Detail"},
		{"SPD7TykYy5w", "Go Class: 27 Concurrent File Processing"},
		{"DtXNSE3Yejg", "Go Class: 28 Conventional Synchronization"},
		{"juBGb6rvoec", "Go Class: 29 Homework #5 (h/w #4 part deux)"},
		{"K1hwpNnCJgY", "Go Class: 30 Concurrency Gotchas"},
		{"oTtYtrFv3gw", "Go Class: 31 Odds & Ends"},
		{"oIxXp0OgK_0", "Go Class: 32 Error Handling"},
		{"T2fqLam1iuk", "Go Class: 33 Reflection"},
		{"7QLoOd9HinY", "Go Class: 34 Mechanical Sympathy"},
		{"nk4rALKLQkc", "Go Class: 35 Benchmarking"},
		{"MDB2x1Di5uM", "Go Class: 36 Profiling"},
		{"GyoMEerSd0I", "Go Class: 37 Static Analysis"},
		{"PIPfNIWVbc8", "Go Class: 38 Testing"},
		{"HfCsfuVqpcM", "Go Class: 39 Code Coverage"},
		{"_N6BxmbLYBk", "Go Class: 40 Go Modules"},
		{"rXgUP_BNyaI", "Go Class: 41 Building Go Programs"},
		{"Si0rAE8yT9g", "Go Class: 42 Parametric Polymorphism"},
		{"i7wbTq-beQo", "Go Class: 43 Parting Thoughts"},
		{"XCE0psygwj8", "Go Class: 13 Regular Expressions & Search"},
	},
	"uz": {
		{"7f5diAAvb-0", "Go Dars 1 Linux Commandalari | Go, Golang Darslari"},
		{"OhaDz3PWcE4", "Go Dars 2 Virtual muhitni shakillantirish Setup Go | Go, Golang Darslari"},
		{"zMqhwd8PsE0", "Go Dars 3 Variable ochish and ASCHII haqida | Go, Golang Darslari"},
		{"I-3QRc5x1VM", "Go Dars 4 Commentlar, Arifmetik operatorlar, Scan yoki input | Go, Golang Darslari"},
		{"McNLNVRl6Ok", "Go Dars 5 if, else, else if, switch | Go, Golang Darslari"},
		{"LqFxOyWQhxM", "Go Dars 6 for | Go, Golang Darslari"},
		{"quid1bYvlzU", "Go Dars 7 array | Go, Golang Darslari"},
		{"tJ8E7XOtXWA", "Go Dars 8 func yoki \"funksiya\" | Go, Golang Darslari"},
		{"G01jZk7hVRc", "Go Dars 9 paketlar va ko`rsatgichlar(pointer) | Go, Golang Darslari"},
		{"FeCqQ69zTaQ", "Go Golangani sozlash | Go, Golang Darslari"},
		{"rdhgkxmdAas", "Go Dars 10 Golangani sozlash va Struck | Go, Golang Darslari"},
		{"2WPnfcBZJDY", "Go Dars 11 String va strings, unicode paketi | Go, Golang Darslari"},
		{"t7LMUEt_AhU", "Go Dars 12 Leetcode | Go, Golang Darslari"},
		{"wog9Lda4uak", "Go Dars 13 Map | Go, Golang Darslari"},
		{"DjjUm6AyWpM", "Go Dars 14 interface | Go, Golang Darslari"},
		{"S1UEUqAKUPA", "Go Dars 15 Goroutines, Time, WaitGroup, Mutex, Select | Go, Golang Darslari"},
		{"2BVGrsk4Hj8", "Go Dars 16 Postgres va Golang bilan CRUD"},
	},
	"ja": {
		{"V1n95q2dIbc", "【Go言語 超入門コース】01.コース紹介｜初心者にわかりやすいようなコースを作りました【プログラミング初心者向け入門講座】"},
		{"P7rC96OhdRs", "【Go言語 超入門コース】02.Goとは？ ｜Goの特徴などをわかりやすく解説【プログラミング初心者向け入門講座】"},
		{"kii-WvV7tDA", "【Go言語 超入門コース】03.環境構築 for Windows｜プログラミングをする準備をしよう！【プログラミング初心者向け入門講座】"},
		{"IlRHVUtMdx4", "[Go Language Beginner Course] 03. Setting up the Development Environment for Mac | Get Ready to P..."},
		{"tj0xjABMb2g", "【Go言語 超入門コース】04.プログラムの3つの基本構造｜プログラムの動きはシンプル。動きは3つだけ【プログラミング初心者向け入門講座】"},
		{"yA65sDbz11M", "[Go Language Super Beginner Course] 05. How to Run a Program | Write a Program and Run It [Introd..."},
		{"yYpMaSHiDpk", "[Go Language Super Beginner Course] 06. Variables | Variables are like \"boxes.\" You can store dat..."},
		{"9xhYPu0PruY", "【Go言語 超入門コース】07.データ型 ｜変数に入れるデータの種類のことです【プログラミング初心者向け入門講座】"},
		{"pMBgsLjSl70", "【Go言語 超入門コース】08.配列｜変数を箱。配列をロッカーに例えて解説します【プログラミング初心者向け入門講座】"},
		{"WOg6XzEHZkI", "【Go言語 超入門コース】09.演算子｜足し算や引き算、2つの値の大小を比較するときに使います【プログラミング初心者向け入門講座】"},
		{"BlauzKUhgTI", "【Go言語 超入門コース】10.条件分岐｜条件にあてはまればAという処理、あてはまらなければBという処理ができます！【プログラミング初心者向け入門講座】"},
		{"ysFSfPze34k", "【Go言語 超入門コース】11.繰り返し｜同じ処理を何度も実行できます【プログラミング初心者向け入門講座】"},
		{"_RC1T9ZJU_0", "【Go言語 超入門コース】12.関数 ｜関数を料理ロボットに例えて説明しました【プログラミング初心者向け入門講座】"},
		{"T4BVT71X3MM", "【Go言語 超入門コース】13.構造体｜構造体ってなんだ？ 異なるデータ型の変数を1つにまとめたもの【プログラミング初心者向け入門講座】"},
		{"D4tEBHbuOos", "【Go言語 超入門コース】14.メソッド｜Goのメソッドは、他の言語のメソッドとは違っています【プログラミング初心者向け入門講座】"},
		{"Ou-a9DjB8Co", "【Go言語 超入門コース】15.実践｜すべて理解できればGoの超入門者から卒業です【プログラミング初心者向け入門講座】"},
		{"kPXfMFJ0oIE", "【たった1時間で学べる】Go言語のプログラミング初心者向けの超入門講座【文字書き起こし、ソースコードも完全無料！】"},
	},
}
