// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity_log.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUserActivityByType = `-- name: CountUserActivityByType :one
SELECT count(*) FROM activity_log
WHERE user_id = $1 AND activity_type = $2
`

type CountUserActivityByTypeParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	ActivityType string      `json:"activity_type"`
}

func (q *Queries) CountUserActivityByType(ctx context.Context, arg CountUserActivityByTypeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserActivityByType, arg.UserID, arg.ActivityType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertActivity = `-- name: InsertActivity :one
INSERT INTO activity_log (user_id, activity_type, ref_type, ref_id, xp_earned)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, activity_type, ref_type, ref_id, xp_earned, occurred_at
`

type InsertActivityParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	ActivityType string      `json:"activity_type"`
	RefType      string      `json:"ref_type"`
	RefID        pgtype.UUID `json:"ref_id"`
	XpEarned     int32       `json:"xp_earned"`
}

func (q *Queries) InsertActivity(ctx context.Context, arg InsertActivityParams) (ActivityLog, error) {
	row := q.db.QueryRow(ctx, insertActivity,
		arg.UserID,
		arg.ActivityType,
		arg.RefType,
		arg.RefID,
		arg.XpEarned,
	)
	var i ActivityLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActivityType,
		&i.RefType,
		&i.RefID,
		&i.XpEarned,
		&i.OccurredAt,
	)
	return i, err
}

const listUserActivity = `-- name: ListUserActivity :many
SELECT id, user_id, activity_type, ref_type, ref_id, xp_earned, occurred_at FROM activity_log
WHERE user_id = $1
ORDER BY occurred_at DESC, id
`

func (q *Queries) ListUserActivity(ctx context.Context, userID pgtype.UUID) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, listUserActivity, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityLog{}
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ActivityType,
			&i.RefType,
			&i.RefID,
			&i.XpEarned,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
