// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_users.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminUpdateUser = `-- name: AdminUpdateUser :one
UPDATE users SET role = $2, is_blocked = $3 WHERE id = $1 RETURNING id, email, password_hash, email_verified, role, is_blocked, display_name, avatar_url, bio, location, locale, is_public, created_at, updated_at
`

type AdminUpdateUserParams struct {
	ID        pgtype.UUID `json:"id"`
	Role      UserRole    `json:"role"`
	IsBlocked bool        `json:"is_blocked"`
}

func (q *Queries) AdminUpdateUser(ctx context.Context, arg AdminUpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, adminUpdateUser, arg.ID, arg.Role, arg.IsBlocked)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.Role,
		&i.IsBlocked,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Location,
		&i.Locale,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
WHERE ($1::text IS NULL
       OR email ILIKE '%' || $1 || '%'
       OR display_name ILIKE '%' || $1 || '%')
`

func (q *Queries) CountUsers(ctx context.Context, q_ pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, q_)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, email_verified, role, is_blocked, display_name, avatar_url, bio, location, locale, is_public, created_at, updated_at FROM users
WHERE ($1::text IS NULL
       OR email ILIKE '%' || $1 || '%'
       OR display_name ILIKE '%' || $1 || '%')
ORDER BY created_at DESC, id
LIMIT $3 OFFSET $2
`

type ListUsersParams struct {
	Q   pgtype.Text `json:"q"`
	Off int32       `json:"off"`
	Lim int32       `json:"lim"`
}

// Optional case-insensitive search over email/display_name, paginated.
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Q, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.EmailVerified,
			&i.Role,
			&i.IsBlocked,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Bio,
			&i.Location,
			&i.Locale,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
