// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (title, slug, body_markdown, difficulty, tags, language)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, title, slug, body_markdown, difficulty, tags, language, created_at, updated_at
`

type CreateArticleParams struct {
	Title        string     `json:"title"`
	Slug         string     `json:"slug"`
	BodyMarkdown string     `json:"body_markdown"`
	Difficulty   Difficulty `json:"difficulty"`
	Tags         []string   `json:"tags"`
	Language     Locale     `json:"language"`
}

// articles --------------------------------------------------------------------
func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, createArticle,
		arg.Title,
		arg.Slug,
		arg.BodyMarkdown,
		arg.Difficulty,
		arg.Tags,
		arg.Language,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.BodyMarkdown,
		&i.Difficulty,
		&i.Tags,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProblem = `-- name: CreateProblem :one
INSERT INTO problems (title, slug, statement_markdown, difficulty, reference_solution_markdown, sample_io, tags, language)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, title, slug, statement_markdown, difficulty, reference_solution_markdown, sample_io, tags, language, created_at, updated_at
`

type CreateProblemParams struct {
	Title                     string     `json:"title"`
	Slug                      string     `json:"slug"`
	StatementMarkdown         string     `json:"statement_markdown"`
	Difficulty                Difficulty `json:"difficulty"`
	ReferenceSolutionMarkdown string     `json:"reference_solution_markdown"`
	SampleIo                  []byte     `json:"sample_io"`
	Tags                      []string   `json:"tags"`
	Language                  Locale     `json:"language"`
}

// problems --------------------------------------------------------------------
func (q *Queries) CreateProblem(ctx context.Context, arg CreateProblemParams) (Problem, error) {
	row := q.db.QueryRow(ctx, createProblem,
		arg.Title,
		arg.Slug,
		arg.StatementMarkdown,
		arg.Difficulty,
		arg.ReferenceSolutionMarkdown,
		arg.SampleIo,
		arg.Tags,
		arg.Language,
	)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.StatementMarkdown,
		&i.Difficulty,
		&i.ReferenceSolutionMarkdown,
		&i.SampleIo,
		&i.Tags,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProblemTestCase = `-- name: CreateProblemTestCase :one
INSERT INTO problem_test_cases (problem_id, input, expected_output, is_sample, position)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, problem_id, input, expected_output, is_sample, position
`

type CreateProblemTestCaseParams struct {
	ProblemID      pgtype.UUID `json:"problem_id"`
	Input          string      `json:"input"`
	ExpectedOutput string      `json:"expected_output"`
	IsSample       bool        `json:"is_sample"`
	Position       int32       `json:"position"`
}

func (q *Queries) CreateProblemTestCase(ctx context.Context, arg CreateProblemTestCaseParams) (ProblemTestCase, error) {
	row := q.db.QueryRow(ctx, createProblemTestCase,
		arg.ProblemID,
		arg.Input,
		arg.ExpectedOutput,
		arg.IsSample,
		arg.Position,
	)
	var i ProblemTestCase
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.Input,
		&i.ExpectedOutput,
		&i.IsSample,
		&i.Position,
	)
	return i, err
}

const createQuiz = `-- name: CreateQuiz :one
INSERT INTO quizzes (title, description, pass_threshold, difficulty, tags, language)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, title, description, pass_threshold, difficulty, tags, language, created_at, updated_at
`

type CreateQuizParams struct {
	Title         string     `json:"title"`
	Description   string     `json:"description"`
	PassThreshold int32      `json:"pass_threshold"`
	Difficulty    Difficulty `json:"difficulty"`
	Tags          []string   `json:"tags"`
	Language      Locale     `json:"language"`
}

// quizzes ---------------------------------------------------------------------
func (q *Queries) CreateQuiz(ctx context.Context, arg CreateQuizParams) (Quiz, error) {
	row := q.db.QueryRow(ctx, createQuiz,
		arg.Title,
		arg.Description,
		arg.PassThreshold,
		arg.Difficulty,
		arg.Tags,
		arg.Language,
	)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.PassThreshold,
		&i.Difficulty,
		&i.Tags,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createQuizOption = `-- name: CreateQuizOption :one
INSERT INTO quiz_options (question_id, text, is_correct, position)
VALUES ($1, $2, $3, $4)
RETURNING id, question_id, text, is_correct, position
`

type CreateQuizOptionParams struct {
	QuestionID pgtype.UUID `json:"question_id"`
	Text       string      `json:"text"`
	IsCorrect  bool        `json:"is_correct"`
	Position   int32       `json:"position"`
}

func (q *Queries) CreateQuizOption(ctx context.Context, arg CreateQuizOptionParams) (QuizOption, error) {
	row := q.db.QueryRow(ctx, createQuizOption,
		arg.QuestionID,
		arg.Text,
		arg.IsCorrect,
		arg.Position,
	)
	var i QuizOption
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Text,
		&i.IsCorrect,
		&i.Position,
	)
	return i, err
}

const createQuizQuestion = `-- name: CreateQuizQuestion :one
INSERT INTO quiz_questions (quiz_id, prompt, type, position)
VALUES ($1, $2, $3, $4)
RETURNING id, quiz_id, prompt, type, position
`

type CreateQuizQuestionParams struct {
	QuizID   pgtype.UUID      `json:"quiz_id"`
	Prompt   string           `json:"prompt"`
	Type     QuizQuestionType `json:"type"`
	Position int32            `json:"position"`
}

func (q *Queries) CreateQuizQuestion(ctx context.Context, arg CreateQuizQuestionParams) (QuizQuestion, error) {
	row := q.db.QueryRow(ctx, createQuizQuestion,
		arg.QuizID,
		arg.Prompt,
		arg.Type,
		arg.Position,
	)
	var i QuizQuestion
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Prompt,
		&i.Type,
		&i.Position,
	)
	return i, err
}

const createVideo = `-- name: CreateVideo :one

INSERT INTO videos (title, description, youtube_id, duration_seconds, difficulty, tags, language)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, title, description, youtube_id, duration_seconds, difficulty, tags, language, created_at, updated_at
`

type CreateVideoParams struct {
	Title           string     `json:"title"`
	Description     string     `json:"description"`
	YoutubeID       string     `json:"youtube_id"`
	DurationSeconds int32      `json:"duration_seconds"`
	Difficulty      Difficulty `json:"difficulty"`
	Tags            []string   `json:"tags"`
	Language        Locale     `json:"language"`
}

// Admin write queries (mutations behind RequireRole("admin")).
// videos ----------------------------------------------------------------------
func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, createVideo,
		arg.Title,
		arg.Description,
		arg.YoutubeID,
		arg.DurationSeconds,
		arg.Difficulty,
		arg.Tags,
		arg.Language,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.YoutubeID,
		&i.DurationSeconds,
		&i.Difficulty,
		&i.Tags,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteArticle = `-- name: DeleteArticle :execrows
DELETE FROM articles WHERE id = $1
`

func (q *Queries) DeleteArticle(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteArticle, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProblem = `-- name: DeleteProblem :execrows
DELETE FROM problems WHERE id = $1
`

func (q *Queries) DeleteProblem(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProblem, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProblemTestCases = `-- name: DeleteProblemTestCases :exec
DELETE FROM problem_test_cases WHERE problem_id = $1
`

func (q *Queries) DeleteProblemTestCases(ctx context.Context, problemID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProblemTestCases, problemID)
	return err
}

const deleteQuiz = `-- name: DeleteQuiz :execrows
DELETE FROM quizzes WHERE id = $1
`

func (q *Queries) DeleteQuiz(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteQuiz, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteQuizQuestions = `-- name: DeleteQuizQuestions :exec
DELETE FROM quiz_questions WHERE quiz_id = $1
`

func (q *Queries) DeleteQuizQuestions(ctx context.Context, quizID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteQuizQuestions, quizID)
	return err
}

const deleteVideo = `-- name: DeleteVideo :execrows
DELETE FROM videos WHERE id = $1
`

func (q *Queries) DeleteVideo(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVideo, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateArticle = `-- name: UpdateArticle :one
UPDATE articles SET
    title = $2, slug = $3, body_markdown = $4, difficulty = $5, tags = $6, language = $7
WHERE id = $1
RETURNING id, title, slug, body_markdown, difficulty, tags, language, created_at, updated_at
`

type UpdateArticleParams struct {
	ID           pgtype.UUID `json:"id"`
	Title        string      `json:"title"`
	Slug         string      `json:"slug"`
	BodyMarkdown string      `json:"body_markdown"`
	Difficulty   Difficulty  `json:"difficulty"`
	Tags         []string    `json:"tags"`
	Language     Locale      `json:"language"`
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, updateArticle,
		arg.ID,
		arg.Title,
		arg.Slug,
		arg.BodyMarkdown,
		arg.Difficulty,
		arg.Tags,
		arg.Language,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.BodyMarkdown,
		&i.Difficulty,
		&i.Tags,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProblem = `-- name: UpdateProblem :one
UPDATE problems SET
    title = $2, slug = $3, statement_markdown = $4, difficulty = $5,
    reference_solution_markdown = $6, sample_io = $7, tags = $8, language = $9
WHERE id = $1
RETURNING id, title, slug, statement_markdown, difficulty, reference_solution_markdown, sample_io, tags, language, created_at, updated_at
`

type UpdateProblemParams struct {
	ID                        pgtype.UUID `json:"id"`
	Title                     string      `json:"title"`
	Slug                      string      `json:"slug"`
	StatementMarkdown         string      `json:"statement_markdown"`
	Difficulty                Difficulty  `json:"difficulty"`
	ReferenceSolutionMarkdown string      `json:"reference_solution_markdown"`
	SampleIo                  []byte      `json:"sample_io"`
	Tags                      []string    `json:"tags"`
	Language                  Locale      `json:"language"`
}

func (q *Queries) UpdateProblem(ctx context.Context, arg UpdateProblemParams) (Problem, error) {
	row := q.db.QueryRow(ctx, updateProblem,
		arg.ID,
		arg.Title,
		arg.Slug,
		arg.StatementMarkdown,
		arg.Difficulty,
		arg.ReferenceSolutionMarkdown,
		arg.SampleIo,
		arg.Tags,
		arg.Language,
	)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.StatementMarkdown,
		&i.Difficulty,
		&i.ReferenceSolutionMarkdown,
		&i.SampleIo,
		&i.Tags,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateQuiz = `-- name: UpdateQuiz :one
UPDATE quizzes SET
    title = $2, description = $3, pass_threshold = $4, difficulty = $5, tags = $6, language = $7
WHERE id = $1
RETURNING id, title, description, pass_threshold, difficulty, tags, language, created_at, updated_at
`

type UpdateQuizParams struct {
	ID            pgtype.UUID `json:"id"`
	Title         string      `json:"title"`
	Description   string      `json:"description"`
	PassThreshold int32       `json:"pass_threshold"`
	Difficulty    Difficulty  `json:"difficulty"`
	Tags          []string    `json:"tags"`
	Language      Locale      `json:"language"`
}

func (q *Queries) UpdateQuiz(ctx context.Context, arg UpdateQuizParams) (Quiz, error) {
	row := q.db.QueryRow(ctx, updateQuiz,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.PassThreshold,
		arg.Difficulty,
		arg.Tags,
		arg.Language,
	)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.PassThreshold,
		&i.Difficulty,
		&i.Tags,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVideo = `-- name: UpdateVideo :one
UPDATE videos SET
    title = $2, description = $3, youtube_id = $4, duration_seconds = $5,
    difficulty = $6, tags = $7, language = $8
WHERE id = $1
RETURNING id, title, description, youtube_id, duration_seconds, difficulty, tags, language, created_at, updated_at
`

type UpdateVideoParams struct {
	ID              pgtype.UUID `json:"id"`
	Title           string      `json:"title"`
	Description     string      `json:"description"`
	YoutubeID       string      `json:"youtube_id"`
	DurationSeconds int32       `json:"duration_seconds"`
	Difficulty      Difficulty  `json:"difficulty"`
	Tags            []string    `json:"tags"`
	Language        Locale      `json:"language"`
}

func (q *Queries) UpdateVideo(ctx context.Context, arg UpdateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, updateVideo,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.YoutubeID,
		arg.DurationSeconds,
		arg.Difficulty,
		arg.Tags,
		arg.Language,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.YoutubeID,
		&i.DurationSeconds,
		&i.Difficulty,
		&i.Tags,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
