// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin2.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBadge = `-- name: CreateBadge :one
INSERT INTO badges (code, title, description, icon, criteria_type, criteria_params)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, code, title, description, icon, criteria_type, criteria_params, created_at
`

type CreateBadgeParams struct {
	Code           string `json:"code"`
	Title          string `json:"title"`
	Description    string `json:"description"`
	Icon           string `json:"icon"`
	CriteriaType   string `json:"criteria_type"`
	CriteriaParams []byte `json:"criteria_params"`
}

// badges ----------------------------------------------------------------------
func (q *Queries) CreateBadge(ctx context.Context, arg CreateBadgeParams) (Badge, error) {
	row := q.db.QueryRow(ctx, createBadge,
		arg.Code,
		arg.Title,
		arg.Description,
		arg.Icon,
		arg.CriteriaType,
		arg.CriteriaParams,
	)
	var i Badge
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Description,
		&i.Icon,
		&i.CriteriaType,
		&i.CriteriaParams,
		&i.CreatedAt,
	)
	return i, err
}

const createCheatsheet = `-- name: CreateCheatsheet :one
INSERT INTO cheatsheets (title, category, body_markdown, language)
VALUES ($1, $2, $3, $4)
RETURNING id, title, category, body_markdown, language, created_at, updated_at
`

type CreateCheatsheetParams struct {
	Title        string `json:"title"`
	Category     string `json:"category"`
	BodyMarkdown string `json:"body_markdown"`
	Language     Locale `json:"language"`
}

// cheatsheets -----------------------------------------------------------------
func (q *Queries) CreateCheatsheet(ctx context.Context, arg CreateCheatsheetParams) (Cheatsheet, error) {
	row := q.db.QueryRow(ctx, createCheatsheet,
		arg.Title,
		arg.Category,
		arg.BodyMarkdown,
		arg.Language,
	)
	var i Cheatsheet
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Category,
		&i.BodyMarkdown,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDailyChallenge = `-- name: CreateDailyChallenge :one
INSERT INTO daily_challenges (challenge_date, content_type, content_id, bonus_xp)
VALUES ($1, $2, $3, $4)
RETURNING id, challenge_date, content_type, content_id, bonus_xp, created_at
`

type CreateDailyChallengeParams struct {
	ChallengeDate pgtype.Date      `json:"challenge_date"`
	ContentType   TrackContentType `json:"content_type"`
	ContentID     pgtype.UUID      `json:"content_id"`
	BonusXp       int32            `json:"bonus_xp"`
}

// daily challenges ------------------------------------------------------------
func (q *Queries) CreateDailyChallenge(ctx context.Context, arg CreateDailyChallengeParams) (DailyChallenge, error) {
	row := q.db.QueryRow(ctx, createDailyChallenge,
		arg.ChallengeDate,
		arg.ContentType,
		arg.ContentID,
		arg.BonusXp,
	)
	var i DailyChallenge
	err := row.Scan(
		&i.ID,
		&i.ChallengeDate,
		&i.ContentType,
		&i.ContentID,
		&i.BonusXp,
		&i.CreatedAt,
	)
	return i, err
}

const createGlossaryTerm = `-- name: CreateGlossaryTerm :one
INSERT INTO glossary_terms (term, definition_markdown, language)
VALUES ($1, $2, $3)
RETURNING id, term, definition_markdown, language, created_at, updated_at
`

type CreateGlossaryTermParams struct {
	Term               string `json:"term"`
	DefinitionMarkdown string `json:"definition_markdown"`
	Language           Locale `json:"language"`
}

// glossary --------------------------------------------------------------------
func (q *Queries) CreateGlossaryTerm(ctx context.Context, arg CreateGlossaryTermParams) (GlossaryTerm, error) {
	row := q.db.QueryRow(ctx, createGlossaryTerm, arg.Term, arg.DefinitionMarkdown, arg.Language)
	var i GlossaryTerm
	err := row.Scan(
		&i.ID,
		&i.Term,
		&i.DefinitionMarkdown,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO mini_projects (title, description_markdown, difficulty, tags, language)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, title, description_markdown, difficulty, tags, language, created_at, updated_at
`

type CreateProjectParams struct {
	Title               string     `json:"title"`
	DescriptionMarkdown string     `json:"description_markdown"`
	Difficulty          Difficulty `json:"difficulty"`
	Tags                []string   `json:"tags"`
	Language            Locale     `json:"language"`
}

// mini projects ---------------------------------------------------------------
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (MiniProject, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Title,
		arg.DescriptionMarkdown,
		arg.Difficulty,
		arg.Tags,
		arg.Language,
	)
	var i MiniProject
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.DescriptionMarkdown,
		&i.Difficulty,
		&i.Tags,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProjectStep = `-- name: CreateProjectStep :one
INSERT INTO mini_project_steps (project_id, text, position)
VALUES ($1, $2, $3)
RETURNING id, project_id, text, position
`

type CreateProjectStepParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Text      string      `json:"text"`
	Position  int32       `json:"position"`
}

func (q *Queries) CreateProjectStep(ctx context.Context, arg CreateProjectStepParams) (MiniProjectStep, error) {
	row := q.db.QueryRow(ctx, createProjectStep, arg.ProjectID, arg.Text, arg.Position)
	var i MiniProjectStep
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Text,
		&i.Position,
	)
	return i, err
}

const createTrack = `-- name: CreateTrack :one

INSERT INTO tracks (title, description, level, position, language)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, title, description, level, position, language, created_at, updated_at
`

type CreateTrackParams struct {
	Title       string     `json:"title"`
	Description string     `json:"description"`
	Level       Difficulty `json:"level"`
	Position    int32      `json:"position"`
	Language    Locale     `json:"language"`
}

// Admin write queries for CHAPTER 13.2 (tracks, cheatsheets, projects, glossary,
// badges, daily challenges). Mounted behind RequireRole("admin").
// tracks ----------------------------------------------------------------------
func (q *Queries) CreateTrack(ctx context.Context, arg CreateTrackParams) (Track, error) {
	row := q.db.QueryRow(ctx, createTrack,
		arg.Title,
		arg.Description,
		arg.Level,
		arg.Position,
		arg.Language,
	)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Level,
		&i.Position,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTrackItem = `-- name: CreateTrackItem :one
INSERT INTO track_items (track_id, content_type, content_id, position)
VALUES ($1, $2, $3, $4)
RETURNING id, track_id, content_type, content_id, position
`

type CreateTrackItemParams struct {
	TrackID     pgtype.UUID      `json:"track_id"`
	ContentType TrackContentType `json:"content_type"`
	ContentID   pgtype.UUID      `json:"content_id"`
	Position    int32            `json:"position"`
}

func (q *Queries) CreateTrackItem(ctx context.Context, arg CreateTrackItemParams) (TrackItem, error) {
	row := q.db.QueryRow(ctx, createTrackItem,
		arg.TrackID,
		arg.ContentType,
		arg.ContentID,
		arg.Position,
	)
	var i TrackItem
	err := row.Scan(
		&i.ID,
		&i.TrackID,
		&i.ContentType,
		&i.ContentID,
		&i.Position,
	)
	return i, err
}

const deleteBadge = `-- name: DeleteBadge :execrows
DELETE FROM badges WHERE id = $1
`

func (q *Queries) DeleteBadge(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBadge, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCheatsheet = `-- name: DeleteCheatsheet :execrows
DELETE FROM cheatsheets WHERE id = $1
`

func (q *Queries) DeleteCheatsheet(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCheatsheet, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDailyChallenge = `-- name: DeleteDailyChallenge :execrows
DELETE FROM daily_challenges WHERE id = $1
`

func (q *Queries) DeleteDailyChallenge(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDailyChallenge, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteGlossaryTerm = `-- name: DeleteGlossaryTerm :execrows
DELETE FROM glossary_terms WHERE id = $1
`

func (q *Queries) DeleteGlossaryTerm(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGlossaryTerm, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProject = `-- name: DeleteProject :execrows
DELETE FROM mini_projects WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProject, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProjectSteps = `-- name: DeleteProjectSteps :exec
DELETE FROM mini_project_steps WHERE project_id = $1
`

func (q *Queries) DeleteProjectSteps(ctx context.Context, projectID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectSteps, projectID)
	return err
}

const deleteTrack = `-- name: DeleteTrack :execrows
DELETE FROM tracks WHERE id = $1
`

func (q *Queries) DeleteTrack(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTrack, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTrackItems = `-- name: DeleteTrackItems :exec
DELETE FROM track_items WHERE track_id = $1
`

func (q *Queries) DeleteTrackItems(ctx context.Context, trackID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTrackItems, trackID)
	return err
}

const updateBadge = `-- name: UpdateBadge :one
UPDATE badges SET code = $2, title = $3, description = $4, icon = $5, criteria_type = $6, criteria_params = $7
WHERE id = $1
RETURNING id, code, title, description, icon, criteria_type, criteria_params, created_at
`

type UpdateBadgeParams struct {
	ID             pgtype.UUID `json:"id"`
	Code           string      `json:"code"`
	Title          string      `json:"title"`
	Description    string      `json:"description"`
	Icon           string      `json:"icon"`
	CriteriaType   string      `json:"criteria_type"`
	CriteriaParams []byte      `json:"criteria_params"`
}

func (q *Queries) UpdateBadge(ctx context.Context, arg UpdateBadgeParams) (Badge, error) {
	row := q.db.QueryRow(ctx, updateBadge,
		arg.ID,
		arg.Code,
		arg.Title,
		arg.Description,
		arg.Icon,
		arg.CriteriaType,
		arg.CriteriaParams,
	)
	var i Badge
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Description,
		&i.Icon,
		&i.CriteriaType,
		&i.CriteriaParams,
		&i.CreatedAt,
	)
	return i, err
}

const updateCheatsheet = `-- name: UpdateCheatsheet :one
UPDATE cheatsheets SET title = $2, category = $3, body_markdown = $4, language = $5
WHERE id = $1
RETURNING id, title, category, body_markdown, language, created_at, updated_at
`

type UpdateCheatsheetParams struct {
	ID           pgtype.UUID `json:"id"`
	Title        string      `json:"title"`
	Category     string      `json:"category"`
	BodyMarkdown string      `json:"body_markdown"`
	Language     Locale      `json:"language"`
}

func (q *Queries) UpdateCheatsheet(ctx context.Context, arg UpdateCheatsheetParams) (Cheatsheet, error) {
	row := q.db.QueryRow(ctx, updateCheatsheet,
		arg.ID,
		arg.Title,
		arg.Category,
		arg.BodyMarkdown,
		arg.Language,
	)
	var i Cheatsheet
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Category,
		&i.BodyMarkdown,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDailyChallenge = `-- name: UpdateDailyChallenge :one
UPDATE daily_challenges SET challenge_date = $2, content_type = $3, content_id = $4, bonus_xp = $5
WHERE id = $1
RETURNING id, challenge_date, content_type, content_id, bonus_xp, created_at
`

type UpdateDailyChallengeParams struct {
	ID            pgtype.UUID      `json:"id"`
	ChallengeDate pgtype.Date      `json:"challenge_date"`
	ContentType   TrackContentType `json:"content_type"`
	ContentID     pgtype.UUID      `json:"content_id"`
	BonusXp       int32            `json:"bonus_xp"`
}

func (q *Queries) UpdateDailyChallenge(ctx context.Context, arg UpdateDailyChallengeParams) (DailyChallenge, error) {
	row := q.db.QueryRow(ctx, updateDailyChallenge,
		arg.ID,
		arg.ChallengeDate,
		arg.ContentType,
		arg.ContentID,
		arg.BonusXp,
	)
	var i DailyChallenge
	err := row.Scan(
		&i.ID,
		&i.ChallengeDate,
		&i.ContentType,
		&i.ContentID,
		&i.BonusXp,
		&i.CreatedAt,
	)
	return i, err
}

const updateGlossaryTerm = `-- name: UpdateGlossaryTerm :one
UPDATE glossary_terms SET term = $2, definition_markdown = $3, language = $4
WHERE id = $1
RETURNING id, term, definition_markdown, language, created_at, updated_at
`

type UpdateGlossaryTermParams struct {
	ID                 pgtype.UUID `json:"id"`
	Term               string      `json:"term"`
	DefinitionMarkdown string      `json:"definition_markdown"`
	Language           Locale      `json:"language"`
}

func (q *Queries) UpdateGlossaryTerm(ctx context.Context, arg UpdateGlossaryTermParams) (GlossaryTerm, error) {
	row := q.db.QueryRow(ctx, updateGlossaryTerm,
		arg.ID,
		arg.Term,
		arg.DefinitionMarkdown,
		arg.Language,
	)
	var i GlossaryTerm
	err := row.Scan(
		&i.ID,
		&i.Term,
		&i.DefinitionMarkdown,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE mini_projects SET title = $2, description_markdown = $3, difficulty = $4, tags = $5, language = $6
WHERE id = $1
RETURNING id, title, description_markdown, difficulty, tags, language, created_at, updated_at
`

type UpdateProjectParams struct {
	ID                  pgtype.UUID `json:"id"`
	Title               string      `json:"title"`
	DescriptionMarkdown string      `json:"description_markdown"`
	Difficulty          Difficulty  `json:"difficulty"`
	Tags                []string    `json:"tags"`
	Language            Locale      `json:"language"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (MiniProject, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Title,
		arg.DescriptionMarkdown,
		arg.Difficulty,
		arg.Tags,
		arg.Language,
	)
	var i MiniProject
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.DescriptionMarkdown,
		&i.Difficulty,
		&i.Tags,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTrack = `-- name: UpdateTrack :one
UPDATE tracks SET title = $2, description = $3, level = $4, position = $5, language = $6
WHERE id = $1
RETURNING id, title, description, level, position, language, created_at, updated_at
`

type UpdateTrackParams struct {
	ID          pgtype.UUID `json:"id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Level       Difficulty  `json:"level"`
	Position    int32       `json:"position"`
	Language    Locale      `json:"language"`
}

func (q *Queries) UpdateTrack(ctx context.Context, arg UpdateTrackParams) (Track, error) {
	row := q.db.QueryRow(ctx, updateTrack,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Level,
		arg.Position,
		arg.Language,
	)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Level,
		&i.Position,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
