// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: article_reads.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getArticleRead = `-- name: GetArticleRead :one
SELECT user_id, article_id, completed_at FROM article_reads WHERE user_id = $1 AND article_id = $2
`

type GetArticleReadParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ArticleID pgtype.UUID `json:"article_id"`
}

func (q *Queries) GetArticleRead(ctx context.Context, arg GetArticleReadParams) (ArticleRead, error) {
	row := q.db.QueryRow(ctx, getArticleRead, arg.UserID, arg.ArticleID)
	var i ArticleRead
	err := row.Scan(&i.UserID, &i.ArticleID, &i.CompletedAt)
	return i, err
}

const markArticleRead = `-- name: MarkArticleRead :one
INSERT INTO article_reads (user_id, article_id)
VALUES ($1, $2)
ON CONFLICT (user_id, article_id) DO NOTHING
RETURNING user_id, article_id, completed_at
`

type MarkArticleReadParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ArticleID pgtype.UUID `json:"article_id"`
}

// Idempotent: returns the new row on first read, or no rows if already read.
func (q *Queries) MarkArticleRead(ctx context.Context, arg MarkArticleReadParams) (ArticleRead, error) {
	row := q.db.QueryRow(ctx, markArticleRead, arg.UserID, arg.ArticleID)
	var i ArticleRead
	err := row.Scan(&i.UserID, &i.ArticleID, &i.CompletedAt)
	return i, err
}
