// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: articles.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countArticles = `-- name: CountArticles :one
SELECT count(*) FROM articles
WHERE ($1::difficulty IS NULL OR difficulty = $1)
  AND ($2::locale     IS NULL OR language = $2)
  AND ($3::text            IS NULL OR $3 = ANY(tags))
  AND ($4::text              IS NULL OR title ILIKE '%' || $4 || '%')
`

type CountArticlesParams struct {
	Difficulty NullDifficulty `json:"difficulty"`
	Language   NullLocale     `json:"language"`
	Tag        pgtype.Text    `json:"tag"`
	Q          pgtype.Text    `json:"q"`
}

func (q *Queries) CountArticles(ctx context.Context, arg CountArticlesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countArticles,
		arg.Difficulty,
		arg.Language,
		arg.Tag,
		arg.Q,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getArticleBySlug = `-- name: GetArticleBySlug :one
SELECT id, title, slug, body_markdown, difficulty, tags, language, created_at, updated_at FROM articles WHERE slug = $1
`

func (q *Queries) GetArticleBySlug(ctx context.Context, slug string) (Article, error) {
	row := q.db.QueryRow(ctx, getArticleBySlug, slug)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.BodyMarkdown,
		&i.Difficulty,
		&i.Tags,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listArticles = `-- name: ListArticles :many
SELECT id, title, slug, body_markdown, difficulty, tags, language, created_at, updated_at FROM articles
WHERE ($1::difficulty IS NULL OR difficulty = $1)
  AND ($2::locale     IS NULL OR language = $2)
  AND ($3::text            IS NULL OR $3 = ANY(tags))
  AND ($4::text              IS NULL OR title ILIKE '%' || $4 || '%')
ORDER BY created_at DESC
LIMIT $6 OFFSET $5
`

type ListArticlesParams struct {
	Difficulty NullDifficulty `json:"difficulty"`
	Language   NullLocale     `json:"language"`
	Tag        pgtype.Text    `json:"tag"`
	Q          pgtype.Text    `json:"q"`
	Off        int32          `json:"off"`
	Lim        int32          `json:"lim"`
}

func (q *Queries) ListArticles(ctx context.Context, arg ListArticlesParams) ([]Article, error) {
	rows, err := q.db.Query(ctx, listArticles,
		arg.Difficulty,
		arg.Language,
		arg.Tag,
		arg.Q,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Article{}
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.BodyMarkdown,
			&i.Difficulty,
			&i.Tags,
			&i.Language,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
