// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: badges.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activityRefCount = `-- name: ActivityRefCount :one
SELECT count(DISTINCT ref_id) FROM activity_log
WHERE user_id = $1
  AND activity_type = $2
  AND ref_id IS NOT NULL
`

type ActivityRefCountParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	ActivityType string      `json:"activity_type"`
}

// Number of distinct referenced entities a user has for an activity type
// (e.g. how many distinct problems were solved).
func (q *Queries) ActivityRefCount(ctx context.Context, arg ActivityRefCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, activityRefCount, arg.UserID, arg.ActivityType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const awardBadge = `-- name: AwardBadge :exec
INSERT INTO user_badges (user_id, badge_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AwardBadgeParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	BadgeID pgtype.UUID `json:"badge_id"`
}

func (q *Queries) AwardBadge(ctx context.Context, arg AwardBadgeParams) error {
	_, err := q.db.Exec(ctx, awardBadge, arg.UserID, arg.BadgeID)
	return err
}

const listUnearnedBadges = `-- name: ListUnearnedBadges :many
SELECT id, code, title, description, icon, criteria_type, criteria_params, created_at FROM badges b
WHERE NOT EXISTS (
    SELECT 1 FROM user_badges ub WHERE ub.badge_id = b.id AND ub.user_id = $1
)
ORDER BY b.code
`

// Badges the user has not yet earned (the engine only evaluates these).
func (q *Queries) ListUnearnedBadges(ctx context.Context, userID pgtype.UUID) ([]Badge, error) {
	rows, err := q.db.Query(ctx, listUnearnedBadges, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Badge{}
	for rows.Next() {
		var i Badge
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Title,
			&i.Description,
			&i.Icon,
			&i.CriteriaType,
			&i.CriteriaParams,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserBadges = `-- name: ListUserBadges :many
SELECT b.code, b.title, b.description, b.icon, ub.awarded_at
FROM user_badges ub
JOIN badges b ON b.id = ub.badge_id
WHERE ub.user_id = $1
ORDER BY ub.awarded_at, b.code
`

type ListUserBadgesRow struct {
	Code        string             `json:"code"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Icon        string             `json:"icon"`
	AwardedAt   pgtype.Timestamptz `json:"awarded_at"`
}

func (q *Queries) ListUserBadges(ctx context.Context, userID pgtype.UUID) ([]ListUserBadgesRow, error) {
	rows, err := q.db.Query(ctx, listUserBadges, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserBadgesRow{}
	for rows.Next() {
		var i ListUserBadgesRow
		if err := rows.Scan(
			&i.Code,
			&i.Title,
			&i.Description,
			&i.Icon,
			&i.AwardedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
