// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookmarks.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBookmark = `-- name: CreateBookmark :one
INSERT INTO bookmarks (user_id, content_type, content_id)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, content_type, content_id)
DO UPDATE SET content_id = EXCLUDED.content_id
RETURNING id, user_id, content_type, content_id, created_at
`

type CreateBookmarkParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	ContentType string      `json:"content_type"`
	ContentID   pgtype.UUID `json:"content_id"`
}

// Idempotent add: a duplicate (user, content) returns the existing row (the
// DO UPDATE is a no-op that lets RETURNING fire on conflict).
func (q *Queries) CreateBookmark(ctx context.Context, arg CreateBookmarkParams) (Bookmark, error) {
	row := q.db.QueryRow(ctx, createBookmark, arg.UserID, arg.ContentType, arg.ContentID)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContentType,
		&i.ContentID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBookmark = `-- name: DeleteBookmark :execrows
DELETE FROM bookmarks WHERE id = $1 AND user_id = $2
`

type DeleteBookmarkParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteBookmark(ctx context.Context, arg DeleteBookmarkParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBookmark, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listUserBookmarks = `-- name: ListUserBookmarks :many
SELECT id, user_id, content_type, content_id, created_at FROM bookmarks WHERE user_id = $1 ORDER BY created_at DESC, id
`

func (q *Queries) ListUserBookmarks(ctx context.Context, userID pgtype.UUID) ([]Bookmark, error) {
	rows, err := q.db.Query(ctx, listUserBookmarks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bookmark{}
	for rows.Next() {
		var i Bookmark
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ContentType,
			&i.ContentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
