// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: certificates.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCertificateByCode = `-- name: GetCertificateByCode :one
SELECT c.certificate_code, c.issued_at, u.display_name, t.title AS track_title
FROM certificates c
JOIN users u ON u.id = c.user_id
JOIN tracks t ON t.id = c.track_id
WHERE c.certificate_code = $1
`

type GetCertificateByCodeRow struct {
	CertificateCode string             `json:"certificate_code"`
	IssuedAt        pgtype.Timestamptz `json:"issued_at"`
	DisplayName     string             `json:"display_name"`
	TrackTitle      string             `json:"track_title"`
}

// Public verification: who earned which track, and when.
func (q *Queries) GetCertificateByCode(ctx context.Context, certificateCode string) (GetCertificateByCodeRow, error) {
	row := q.db.QueryRow(ctx, getCertificateByCode, certificateCode)
	var i GetCertificateByCodeRow
	err := row.Scan(
		&i.CertificateCode,
		&i.IssuedAt,
		&i.DisplayName,
		&i.TrackTitle,
	)
	return i, err
}

const getUserTrackCertificate = `-- name: GetUserTrackCertificate :one
SELECT id, user_id, track_id, certificate_code, issued_at FROM certificates WHERE user_id = $1 AND track_id = $2
`

type GetUserTrackCertificateParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	TrackID pgtype.UUID `json:"track_id"`
}

func (q *Queries) GetUserTrackCertificate(ctx context.Context, arg GetUserTrackCertificateParams) (Certificate, error) {
	row := q.db.QueryRow(ctx, getUserTrackCertificate, arg.UserID, arg.TrackID)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TrackID,
		&i.CertificateCode,
		&i.IssuedAt,
	)
	return i, err
}

const issueCertificate = `-- name: IssueCertificate :one
INSERT INTO certificates (user_id, track_id, certificate_code)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, track_id) DO NOTHING
RETURNING id, user_id, track_id, certificate_code, issued_at
`

type IssueCertificateParams struct {
	UserID          pgtype.UUID `json:"user_id"`
	TrackID         pgtype.UUID `json:"track_id"`
	CertificateCode string      `json:"certificate_code"`
}

// Issues a certificate once per (user, track); a repeat conflicts and returns no
// rows (the caller then fetches the existing one).
func (q *Queries) IssueCertificate(ctx context.Context, arg IssueCertificateParams) (Certificate, error) {
	row := q.db.QueryRow(ctx, issueCertificate, arg.UserID, arg.TrackID, arg.CertificateCode)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TrackID,
		&i.CertificateCode,
		&i.IssuedAt,
	)
	return i, err
}

const listUserCertificates = `-- name: ListUserCertificates :many
SELECT c.id, c.certificate_code, c.issued_at, c.track_id, t.title AS track_title
FROM certificates c
JOIN tracks t ON t.id = c.track_id
WHERE c.user_id = $1
ORDER BY c.issued_at DESC, c.id
`

type ListUserCertificatesRow struct {
	ID              pgtype.UUID        `json:"id"`
	CertificateCode string             `json:"certificate_code"`
	IssuedAt        pgtype.Timestamptz `json:"issued_at"`
	TrackID         pgtype.UUID        `json:"track_id"`
	TrackTitle      string             `json:"track_title"`
}

func (q *Queries) ListUserCertificates(ctx context.Context, userID pgtype.UUID) ([]ListUserCertificatesRow, error) {
	rows, err := q.db.Query(ctx, listUserCertificates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserCertificatesRow{}
	for rows.Next() {
		var i ListUserCertificatesRow
		if err := rows.Scan(
			&i.ID,
			&i.CertificateCode,
			&i.IssuedAt,
			&i.TrackID,
			&i.TrackTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
