// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cheatsheets.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCheatsheets = `-- name: CountCheatsheets :one
SELECT count(*) FROM cheatsheets
WHERE ($1::text IS NULL OR category = $1)
  AND ($2::locale IS NULL OR language = $2)
  AND ($3::text IS NULL
       OR title ILIKE '%' || $3 || '%'
       OR category ILIKE '%' || $3 || '%')
`

type CountCheatsheetsParams struct {
	Category pgtype.Text `json:"category"`
	Language NullLocale  `json:"language"`
	Q        pgtype.Text `json:"q"`
}

func (q *Queries) CountCheatsheets(ctx context.Context, arg CountCheatsheetsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCheatsheets, arg.Category, arg.Language, arg.Q)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCheatsheetByID = `-- name: GetCheatsheetByID :one
SELECT id, title, category, body_markdown, language, created_at, updated_at FROM cheatsheets WHERE id = $1
`

func (q *Queries) GetCheatsheetByID(ctx context.Context, id pgtype.UUID) (Cheatsheet, error) {
	row := q.db.QueryRow(ctx, getCheatsheetByID, id)
	var i Cheatsheet
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Category,
		&i.BodyMarkdown,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCheatsheets = `-- name: ListCheatsheets :many
SELECT id, title, category, body_markdown, language, created_at, updated_at FROM cheatsheets
WHERE ($1::text IS NULL OR category = $1)
  AND ($2::locale IS NULL OR language = $2)
  AND ($3::text IS NULL
       OR title ILIKE '%' || $3 || '%'
       OR category ILIKE '%' || $3 || '%')
ORDER BY category, title
LIMIT $5 OFFSET $4
`

type ListCheatsheetsParams struct {
	Category pgtype.Text `json:"category"`
	Language NullLocale  `json:"language"`
	Q        pgtype.Text `json:"q"`
	Off      int32       `json:"off"`
	Lim      int32       `json:"lim"`
}

func (q *Queries) ListCheatsheets(ctx context.Context, arg ListCheatsheetsParams) ([]Cheatsheet, error) {
	rows, err := q.db.Query(ctx, listCheatsheets,
		arg.Category,
		arg.Language,
		arg.Q,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cheatsheet{}
	for rows.Next() {
		var i Cheatsheet
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Category,
			&i.BodyMarkdown,
			&i.Language,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
