package store

// Hand-written companions to the sqlc-generated by-slug lookups. sqlc owns the
// *.sql.go files; these by-id variants live here so the content can be addressed
// by its stable UUID as well as its slug (used by track-program navigation,
// where items reference content polymorphically by id). They mirror the
// generated query style exactly and read q.db like any other Queries method.

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getArticleByID = `-- name: GetArticleByID :one
SELECT id, title, slug, body_markdown, difficulty, tags, language, created_at, updated_at FROM articles WHERE id = $1
`

func (q *Queries) GetArticleByID(ctx context.Context, id pgtype.UUID) (Article, error) {
	row := q.db.QueryRow(ctx, getArticleByID, id)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.BodyMarkdown,
		&i.Difficulty,
		&i.Tags,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProblemByID = `-- name: GetProblemByID :one
SELECT id, title, slug, statement_markdown, difficulty, reference_solution_markdown, sample_io, tags, language, created_at, updated_at FROM problems WHERE id = $1
`

func (q *Queries) GetProblemByID(ctx context.Context, id pgtype.UUID) (Problem, error) {
	row := q.db.QueryRow(ctx, getProblemByID, id)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.StatementMarkdown,
		&i.Difficulty,
		&i.ReferenceSolutionMarkdown,
		&i.SampleIo,
		&i.Tags,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
