// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daily_challenges.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeDailyChallenge = `-- name: CompleteDailyChallenge :one
INSERT INTO user_daily_challenges (user_id, challenge_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
RETURNING completed_at
`

type CompleteDailyChallengeParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	ChallengeID pgtype.UUID `json:"challenge_id"`
}

// Marks the challenge done for the user. Returns the completion time the first
// time; a repeat conflicts and returns no rows (idempotent — no double reward).
func (q *Queries) CompleteDailyChallenge(ctx context.Context, arg CompleteDailyChallengeParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, completeDailyChallenge, arg.UserID, arg.ChallengeID)
	var completed_at pgtype.Timestamptz
	err := row.Scan(&completed_at)
	return completed_at, err
}

const getDailyChallengeByDate = `-- name: GetDailyChallengeByDate :one
SELECT id, challenge_date, content_type, content_id, bonus_xp, created_at FROM daily_challenges WHERE challenge_date = $1
`

func (q *Queries) GetDailyChallengeByDate(ctx context.Context, challengeDate pgtype.Date) (DailyChallenge, error) {
	row := q.db.QueryRow(ctx, getDailyChallengeByDate, challengeDate)
	var i DailyChallenge
	err := row.Scan(
		&i.ID,
		&i.ChallengeDate,
		&i.ContentType,
		&i.ContentID,
		&i.BonusXp,
		&i.CreatedAt,
	)
	return i, err
}

const isDailyChallengeCompleted = `-- name: IsDailyChallengeCompleted :one
SELECT EXISTS(
    SELECT 1 FROM user_daily_challenges
    WHERE user_id = $1 AND challenge_id = $2
)
`

type IsDailyChallengeCompletedParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	ChallengeID pgtype.UUID `json:"challenge_id"`
}

func (q *Queries) IsDailyChallengeCompleted(ctx context.Context, arg IsDailyChallengeCompletedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isDailyChallengeCompleted, arg.UserID, arg.ChallengeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
