// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: glossary.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countGlossaryTerms = `-- name: CountGlossaryTerms :one
SELECT count(*) FROM glossary_terms
WHERE ($1::locale IS NULL OR language = $1)
  AND ($2::text IS NULL
       OR term ILIKE '%' || $2 || '%'
       OR definition_markdown ILIKE '%' || $2 || '%')
`

type CountGlossaryTermsParams struct {
	Language NullLocale  `json:"language"`
	Q        pgtype.Text `json:"q"`
}

func (q *Queries) CountGlossaryTerms(ctx context.Context, arg CountGlossaryTermsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countGlossaryTerms, arg.Language, arg.Q)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listGlossaryTerms = `-- name: ListGlossaryTerms :many
SELECT id, term, definition_markdown, language, created_at, updated_at FROM glossary_terms
WHERE ($1::locale IS NULL OR language = $1)
  AND ($2::text IS NULL
       OR term ILIKE '%' || $2 || '%'
       OR definition_markdown ILIKE '%' || $2 || '%')
ORDER BY term
LIMIT $4 OFFSET $3
`

type ListGlossaryTermsParams struct {
	Language NullLocale  `json:"language"`
	Q        pgtype.Text `json:"q"`
	Off      int32       `json:"off"`
	Lim      int32       `json:"lim"`
}

func (q *Queries) ListGlossaryTerms(ctx context.Context, arg ListGlossaryTermsParams) ([]GlossaryTerm, error) {
	rows, err := q.db.Query(ctx, listGlossaryTerms,
		arg.Language,
		arg.Q,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GlossaryTerm{}
	for rows.Next() {
		var i GlossaryTerm
		if err := rows.Scan(
			&i.ID,
			&i.Term,
			&i.DefinitionMarkdown,
			&i.Language,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
