// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const now = `-- name: Now :one
SELECT now()::timestamptz AS now
`

// Demo query proving the sqlc pipeline end-to-end; also usable as a DB liveness probe.
func (q *Queries) Now(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, now)
	var now pgtype.Timestamptz
	err := row.Scan(&now)
	return now, err
}
