// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leaderboard.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const leaderboardAllTime = `-- name: LeaderboardAllTime :many
SELECT u.id, u.display_name, u.avatar_url, us.total_xp::bigint AS xp
FROM user_stats us
JOIN users u ON u.id = us.user_id
WHERE u.is_public AND NOT u.is_blocked
ORDER BY us.total_xp DESC, u.id
LIMIT $2 OFFSET $1
`

type LeaderboardAllTimeParams struct {
	Off int32 `json:"off"`
	Lim int32 `json:"lim"`
}

type LeaderboardAllTimeRow struct {
	ID          pgtype.UUID `json:"id"`
	DisplayName string      `json:"display_name"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	Xp          int64       `json:"xp"`
}

// Public, non-blocked users ranked by lifetime XP.
func (q *Queries) LeaderboardAllTime(ctx context.Context, arg LeaderboardAllTimeParams) ([]LeaderboardAllTimeRow, error) {
	rows, err := q.db.Query(ctx, leaderboardAllTime, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeaderboardAllTimeRow{}
	for rows.Next() {
		var i LeaderboardAllTimeRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Xp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const leaderboardPeriod = `-- name: LeaderboardPeriod :many
SELECT u.id, u.display_name, u.avatar_url, COALESCE(SUM(al.xp_earned), 0)::bigint AS xp
FROM users u
JOIN activity_log al ON al.user_id = u.id
WHERE u.is_public AND NOT u.is_blocked
  AND al.occurred_at >= $1
  AND al.occurred_at <  $2
GROUP BY u.id, u.display_name, u.avatar_url
HAVING COALESCE(SUM(al.xp_earned), 0) > 0
ORDER BY xp DESC, u.id
LIMIT $4 OFFSET $3
`

type LeaderboardPeriodParams struct {
	FromTs pgtype.Timestamptz `json:"from_ts"`
	ToTs   pgtype.Timestamptz `json:"to_ts"`
	Off    int32              `json:"off"`
	Lim    int32              `json:"lim"`
}

type LeaderboardPeriodRow struct {
	ID          pgtype.UUID `json:"id"`
	DisplayName string      `json:"display_name"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	Xp          int64       `json:"xp"`
}

// Public, non-blocked users ranked by XP earned in the half-open window [from, to).
func (q *Queries) LeaderboardPeriod(ctx context.Context, arg LeaderboardPeriodParams) ([]LeaderboardPeriodRow, error) {
	rows, err := q.db.Query(ctx, leaderboardPeriod,
		arg.FromTs,
		arg.ToTs,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeaderboardPeriodRow{}
	for rows.Next() {
		var i LeaderboardPeriodRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Xp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
