// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: me_progress.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activityHeatmap = `-- name: ActivityHeatmap :many
SELECT
    to_char((occurred_at AT TIME ZONE 'UTC')::date, 'YYYY-MM-DD') AS day,
    count(*)                            AS count,
    coalesce(sum(xp_earned), 0)::bigint AS xp
FROM activity_log
WHERE user_id = $1
  AND occurred_at >= $2
  AND occurred_at <  $3
GROUP BY day
ORDER BY day
`

type ActivityHeatmapParams struct {
	UserID pgtype.UUID        `json:"user_id"`
	FromTs pgtype.Timestamptz `json:"from_ts"`
	ToTs   pgtype.Timestamptz `json:"to_ts"`
}

type ActivityHeatmapRow struct {
	Day   string `json:"day"`
	Count int64  `json:"count"`
	Xp    int64  `json:"xp"`
}

// Daily activity buckets in UTC (D-010) over the half-open range [from_ts, to_ts).
func (q *Queries) ActivityHeatmap(ctx context.Context, arg ActivityHeatmapParams) ([]ActivityHeatmapRow, error) {
	rows, err := q.db.Query(ctx, activityHeatmap, arg.UserID, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityHeatmapRow{}
	for rows.Next() {
		var i ActivityHeatmapRow
		if err := rows.Scan(&i.Day, &i.Count, &i.Xp); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const progressSummary = `-- name: ProgressSummary :one
SELECT
    (SELECT count(*) FROM video_progress vp
        WHERE vp.user_id = $1 AND vp.completed)                  AS videos_completed,
    (SELECT count(*) FROM article_reads ar
        WHERE ar.user_id = $1)                                  AS articles_read,
    (SELECT count(DISTINCT qa.quiz_id) FROM quiz_attempts qa
        WHERE qa.user_id = $1 AND qa.passed)                    AS quizzes_passed,
    (SELECT count(DISTINCT ps.problem_id) FROM problem_submissions ps
        WHERE ps.user_id = $1 AND ps.status = 'solved')         AS problems_solved,
    (SELECT count(*) FROM project_progress pp
        JOIN (
            SELECT mps.project_id, count(*) AS step_count
            FROM mini_project_steps mps GROUP BY mps.project_id
        ) s ON s.project_id = pp.project_id
        WHERE pp.user_id = $1
          AND jsonb_array_length(pp.completed_steps) >= s.step_count)            AS projects_completed
`

type ProgressSummaryRow struct {
	VideosCompleted   int64 `json:"videos_completed"`
	ArticlesRead      int64 `json:"articles_read"`
	QuizzesPassed     int64 `json:"quizzes_passed"`
	ProblemsSolved    int64 `json:"problems_solved"`
	ProjectsCompleted int64 `json:"projects_completed"`
}

// Per-section completion counts for the authenticated user's dashboard.
// Every column is alias-qualified: sqlc merges the scalar-subquery scopes, so an
// unqualified user_id would read as ambiguous across the joined-in tables.
func (q *Queries) ProgressSummary(ctx context.Context, userID pgtype.UUID) (ProgressSummaryRow, error) {
	row := q.db.QueryRow(ctx, progressSummary, userID)
	var i ProgressSummaryRow
	err := row.Scan(
		&i.VideosCompleted,
		&i.ArticlesRead,
		&i.QuizzesPassed,
		&i.ProblemsSolved,
		&i.ProjectsCompleted,
	)
	return i, err
}
