// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mini_projects.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProjects = `-- name: CountProjects :one
SELECT count(*) FROM mini_projects
WHERE ($1::difficulty IS NULL OR difficulty = $1)
  AND ($2::locale     IS NULL OR language = $2)
  AND ($3::text            IS NULL OR $3 = ANY(tags))
  AND ($4::text              IS NULL OR title ILIKE '%' || $4 || '%')
  AND ($5::bool OR NOT ('hidden' = ANY(tags)))
`

type CountProjectsParams struct {
	Difficulty NullDifficulty `json:"difficulty"`
	Language   NullLocale     `json:"language"`
	Tag        pgtype.Text    `json:"tag"`
	Q          pgtype.Text    `json:"q"`
	ShowHidden bool           `json:"show_hidden"`
}

func (q *Queries) CountProjects(ctx context.Context, arg CountProjectsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProjects,
		arg.Difficulty,
		arg.Language,
		arg.Tag,
		arg.Q,
		arg.ShowHidden,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, title, description_markdown, difficulty, tags, language, created_at, updated_at FROM mini_projects WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id pgtype.UUID) (MiniProject, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i MiniProject
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.DescriptionMarkdown,
		&i.Difficulty,
		&i.Tags,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectProgress = `-- name: GetProjectProgress :one
SELECT user_id, project_id, completed_steps, updated_at FROM project_progress WHERE user_id = $1 AND project_id = $2
`

type GetProjectProgressParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) GetProjectProgress(ctx context.Context, arg GetProjectProgressParams) (ProjectProgress, error) {
	row := q.db.QueryRow(ctx, getProjectProgress, arg.UserID, arg.ProjectID)
	var i ProjectProgress
	err := row.Scan(
		&i.UserID,
		&i.ProjectID,
		&i.CompletedSteps,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectSteps = `-- name: ListProjectSteps :many
SELECT id, project_id, text, position FROM mini_project_steps WHERE project_id = $1 ORDER BY position, id
`

func (q *Queries) ListProjectSteps(ctx context.Context, projectID pgtype.UUID) ([]MiniProjectStep, error) {
	rows, err := q.db.Query(ctx, listProjectSteps, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MiniProjectStep{}
	for rows.Next() {
		var i MiniProjectStep
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Text,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, title, description_markdown, difficulty, tags, language, created_at, updated_at FROM mini_projects
WHERE ($1::difficulty IS NULL OR difficulty = $1)
  AND ($2::locale     IS NULL OR language = $2)
  AND ($3::text            IS NULL OR $3 = ANY(tags))
  AND ($4::text              IS NULL OR title ILIKE '%' || $4 || '%')
  AND ($5::bool OR NOT ('hidden' = ANY(tags)))
ORDER BY created_at DESC
LIMIT $7 OFFSET $6
`

type ListProjectsParams struct {
	Difficulty NullDifficulty `json:"difficulty"`
	Language   NullLocale     `json:"language"`
	Tag        pgtype.Text    `json:"tag"`
	Q          pgtype.Text    `json:"q"`
	ShowHidden bool           `json:"show_hidden"`
	Off        int32          `json:"off"`
	Lim        int32          `json:"lim"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]MiniProject, error) {
	rows, err := q.db.Query(ctx, listProjects,
		arg.Difficulty,
		arg.Language,
		arg.Tag,
		arg.Q,
		arg.ShowHidden,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MiniProject{}
	for rows.Next() {
		var i MiniProject
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.DescriptionMarkdown,
			&i.Difficulty,
			&i.Tags,
			&i.Language,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProjectProgress = `-- name: UpsertProjectProgress :one
INSERT INTO project_progress (user_id, project_id, completed_steps)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, project_id) DO UPDATE SET completed_steps = EXCLUDED.completed_steps
RETURNING user_id, project_id, completed_steps, updated_at
`

type UpsertProjectProgressParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
	CompletedSteps []byte      `json:"completed_steps"`
}

func (q *Queries) UpsertProjectProgress(ctx context.Context, arg UpsertProjectProgressParams) (ProjectProgress, error) {
	row := q.db.QueryRow(ctx, upsertProjectProgress, arg.UserID, arg.ProjectID, arg.CompletedSteps)
	var i ProjectProgress
	err := row.Scan(
		&i.UserID,
		&i.ProjectID,
		&i.CompletedSteps,
		&i.UpdatedAt,
	)
	return i, err
}
