// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Difficulty string

const (
	DifficultyBeginner     Difficulty = "beginner"
	DifficultyIntermediate Difficulty = "intermediate"
	DifficultyAdvanced     Difficulty = "advanced"
)

func (e *Difficulty) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Difficulty(s)
	case string:
		*e = Difficulty(s)
	default:
		return fmt.Errorf("unsupported scan type for Difficulty: %T", src)
	}
	return nil
}

type NullDifficulty struct {
	Difficulty Difficulty `json:"difficulty"`
	Valid      bool       `json:"valid"` // Valid is true if Difficulty is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDifficulty) Scan(value interface{}) error {
	if value == nil {
		ns.Difficulty, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Difficulty.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDifficulty) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Difficulty), nil
}

type Locale string

const (
	LocaleRu Locale = "ru"
	LocaleEn Locale = "en"
	LocaleUz Locale = "uz"
	LocaleJa Locale = "ja"
)

func (e *Locale) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Locale(s)
	case string:
		*e = Locale(s)
	default:
		return fmt.Errorf("unsupported scan type for Locale: %T", src)
	}
	return nil
}

type NullLocale struct {
	Locale Locale `json:"locale"`
	Valid  bool   `json:"valid"` // Valid is true if Locale is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLocale) Scan(value interface{}) error {
	if value == nil {
		ns.Locale, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Locale.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLocale) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Locale), nil
}

type QuizQuestionType string

const (
	QuizQuestionTypeSingle   QuizQuestionType = "single"
	QuizQuestionTypeMultiple QuizQuestionType = "multiple"
)

func (e *QuizQuestionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QuizQuestionType(s)
	case string:
		*e = QuizQuestionType(s)
	default:
		return fmt.Errorf("unsupported scan type for QuizQuestionType: %T", src)
	}
	return nil
}

type NullQuizQuestionType struct {
	QuizQuestionType QuizQuestionType `json:"quiz_question_type"`
	Valid            bool             `json:"valid"` // Valid is true if QuizQuestionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQuizQuestionType) Scan(value interface{}) error {
	if value == nil {
		ns.QuizQuestionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QuizQuestionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQuizQuestionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QuizQuestionType), nil
}

type SubmissionStatus string

const (
	SubmissionStatusAttempted SubmissionStatus = "attempted"
	SubmissionStatusSolved    SubmissionStatus = "solved"
)

func (e *SubmissionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubmissionStatus(s)
	case string:
		*e = SubmissionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SubmissionStatus: %T", src)
	}
	return nil
}

type NullSubmissionStatus struct {
	SubmissionStatus SubmissionStatus `json:"submission_status"`
	Valid            bool             `json:"valid"` // Valid is true if SubmissionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubmissionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SubmissionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubmissionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubmissionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubmissionStatus), nil
}

type TrackContentType string

const (
	TrackContentTypeVideo   TrackContentType = "video"
	TrackContentTypeArticle TrackContentType = "article"
	TrackContentTypeQuiz    TrackContentType = "quiz"
	TrackContentTypeProblem TrackContentType = "problem"
	TrackContentTypeProject TrackContentType = "project"
)

func (e *TrackContentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TrackContentType(s)
	case string:
		*e = TrackContentType(s)
	default:
		return fmt.Errorf("unsupported scan type for TrackContentType: %T", src)
	}
	return nil
}

type NullTrackContentType struct {
	TrackContentType TrackContentType `json:"track_content_type"`
	Valid            bool             `json:"valid"` // Valid is true if TrackContentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTrackContentType) Scan(value interface{}) error {
	if value == nil {
		ns.TrackContentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TrackContentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTrackContentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TrackContentType), nil
}

type UserRole string

const (
	UserRoleStudent UserRole = "student"
	UserRoleAdmin   UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type ActivityLog struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	ActivityType string             `json:"activity_type"`
	RefType      string             `json:"ref_type"`
	RefID        pgtype.UUID        `json:"ref_id"`
	XpEarned     int32              `json:"xp_earned"`
	OccurredAt   pgtype.Timestamptz `json:"occurred_at"`
}

type Article struct {
	ID           pgtype.UUID        `json:"id"`
	Title        string             `json:"title"`
	Slug         string             `json:"slug"`
	BodyMarkdown string             `json:"body_markdown"`
	Difficulty   Difficulty         `json:"difficulty"`
	Tags         []string           `json:"tags"`
	Language     Locale             `json:"language"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ArticleRead struct {
	UserID      pgtype.UUID        `json:"user_id"`
	ArticleID   pgtype.UUID        `json:"article_id"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

type Badge struct {
	ID             pgtype.UUID        `json:"id"`
	Code           string             `json:"code"`
	Title          string             `json:"title"`
	Description    string             `json:"description"`
	Icon           string             `json:"icon"`
	CriteriaType   string             `json:"criteria_type"`
	CriteriaParams []byte             `json:"criteria_params"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Bookmark struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	ContentType string             `json:"content_type"`
	ContentID   pgtype.UUID        `json:"content_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Certificate struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	TrackID         pgtype.UUID        `json:"track_id"`
	CertificateCode string             `json:"certificate_code"`
	IssuedAt        pgtype.Timestamptz `json:"issued_at"`
}

type Cheatsheet struct {
	ID           pgtype.UUID        `json:"id"`
	Title        string             `json:"title"`
	Category     string             `json:"category"`
	BodyMarkdown string             `json:"body_markdown"`
	Language     Locale             `json:"language"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type DailyChallenge struct {
	ID            pgtype.UUID        `json:"id"`
	ChallengeDate pgtype.Date        `json:"challenge_date"`
	ContentType   TrackContentType   `json:"content_type"`
	ContentID     pgtype.UUID        `json:"content_id"`
	BonusXp       int32              `json:"bonus_xp"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type EmailVerificationToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type GlossaryTerm struct {
	ID                 pgtype.UUID        `json:"id"`
	Term               string             `json:"term"`
	DefinitionMarkdown string             `json:"definition_markdown"`
	Language           Locale             `json:"language"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type MiniProject struct {
	ID                  pgtype.UUID        `json:"id"`
	Title               string             `json:"title"`
	DescriptionMarkdown string             `json:"description_markdown"`
	Difficulty          Difficulty         `json:"difficulty"`
	Tags                []string           `json:"tags"`
	Language            Locale             `json:"language"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type MiniProjectStep struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
	Text      string      `json:"text"`
	Position  int32       `json:"position"`
}

type Note struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	ContentType string             `json:"content_type"`
	ContentID   pgtype.UUID        `json:"content_id"`
	Body        string             `json:"body"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type PasswordResetToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Problem struct {
	ID                        pgtype.UUID        `json:"id"`
	Title                     string             `json:"title"`
	Slug                      string             `json:"slug"`
	StatementMarkdown         string             `json:"statement_markdown"`
	Difficulty                Difficulty         `json:"difficulty"`
	ReferenceSolutionMarkdown string             `json:"reference_solution_markdown"`
	SampleIo                  []byte             `json:"sample_io"`
	Tags                      []string           `json:"tags"`
	Language                  Locale             `json:"language"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

type ProblemSubmission struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	ProblemID pgtype.UUID        `json:"problem_id"`
	Status    SubmissionStatus   `json:"status"`
	Code      string             `json:"code"`
	Language  string             `json:"language"`
	Verdict   []byte             `json:"verdict"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ProblemTestCase struct {
	ID             pgtype.UUID `json:"id"`
	ProblemID      pgtype.UUID `json:"problem_id"`
	Input          string      `json:"input"`
	ExpectedOutput string      `json:"expected_output"`
	IsSample       bool        `json:"is_sample"`
	Position       int32       `json:"position"`
}

type ProjectProgress struct {
	UserID         pgtype.UUID        `json:"user_id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	CompletedSteps []byte             `json:"completed_steps"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Quiz struct {
	ID            pgtype.UUID        `json:"id"`
	Title         string             `json:"title"`
	Description   string             `json:"description"`
	PassThreshold int32              `json:"pass_threshold"`
	Difficulty    Difficulty         `json:"difficulty"`
	Tags          []string           `json:"tags"`
	Language      Locale             `json:"language"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type QuizAttempt struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	QuizID    pgtype.UUID        `json:"quiz_id"`
	Score     int32              `json:"score"`
	Passed    bool               `json:"passed"`
	Answers   []byte             `json:"answers"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type QuizOption struct {
	ID         pgtype.UUID `json:"id"`
	QuestionID pgtype.UUID `json:"question_id"`
	Text       string      `json:"text"`
	IsCorrect  bool        `json:"is_correct"`
	Position   int32       `json:"position"`
}

type QuizQuestion struct {
	ID       pgtype.UUID      `json:"id"`
	QuizID   pgtype.UUID      `json:"quiz_id"`
	Prompt   string           `json:"prompt"`
	Type     QuizQuestionType `json:"type"`
	Position int32            `json:"position"`
}

type RefreshSession struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	FamilyID  pgtype.UUID        `json:"family_id"`
	TokenHash string             `json:"token_hash"`
	UserAgent string             `json:"user_agent"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Track struct {
	ID          pgtype.UUID        `json:"id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Level       Difficulty         `json:"level"`
	Position    int32              `json:"position"`
	Language    Locale             `json:"language"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type TrackEnrollment struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TrackID   pgtype.UUID        `json:"track_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type TrackItem struct {
	ID          pgtype.UUID      `json:"id"`
	TrackID     pgtype.UUID      `json:"track_id"`
	ContentType TrackContentType `json:"content_type"`
	ContentID   pgtype.UUID      `json:"content_id"`
	Position    int32            `json:"position"`
}

type User struct {
	ID            pgtype.UUID        `json:"id"`
	Email         string             `json:"email"`
	PasswordHash  string             `json:"password_hash"`
	EmailVerified bool               `json:"email_verified"`
	Role          UserRole           `json:"role"`
	IsBlocked     bool               `json:"is_blocked"`
	DisplayName   string             `json:"display_name"`
	AvatarUrl     pgtype.Text        `json:"avatar_url"`
	Bio           string             `json:"bio"`
	Location      string             `json:"location"`
	Locale        Locale             `json:"locale"`
	IsPublic      bool               `json:"is_public"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type UserBadge struct {
	UserID    pgtype.UUID        `json:"user_id"`
	BadgeID   pgtype.UUID        `json:"badge_id"`
	AwardedAt pgtype.Timestamptz `json:"awarded_at"`
}

type UserDailyChallenge struct {
	UserID      pgtype.UUID        `json:"user_id"`
	ChallengeID pgtype.UUID        `json:"challenge_id"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

type UserStat struct {
	UserID         pgtype.UUID        `json:"user_id"`
	TotalXp        int32              `json:"total_xp"`
	Level          int32              `json:"level"`
	CurrentStreak  int32              `json:"current_streak"`
	LongestStreak  int32              `json:"longest_streak"`
	LastActiveDate pgtype.Date        `json:"last_active_date"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Video struct {
	ID              pgtype.UUID        `json:"id"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	YoutubeID       string             `json:"youtube_id"`
	DurationSeconds int32              `json:"duration_seconds"`
	Difficulty      Difficulty         `json:"difficulty"`
	Tags            []string           `json:"tags"`
	Language        Locale             `json:"language"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type VideoProgress struct {
	UserID              pgtype.UUID        `json:"user_id"`
	VideoID             pgtype.UUID        `json:"video_id"`
	WatchedPercent      int32              `json:"watched_percent"`
	LastPositionSeconds int32              `json:"last_position_seconds"`
	Completed           bool               `json:"completed"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}
