// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (user_id, content_type, content_id, body)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, content_type, content_id, body, created_at, updated_at
`

type CreateNoteParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	ContentType string      `json:"content_type"`
	ContentID   pgtype.UUID `json:"content_id"`
	Body        string      `json:"body"`
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, createNote,
		arg.UserID,
		arg.ContentType,
		arg.ContentID,
		arg.Body,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContentType,
		&i.ContentID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :execrows
DELETE FROM notes WHERE id = $1 AND user_id = $2
`

type DeleteNoteParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteNote(ctx context.Context, arg DeleteNoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNote, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listUserNotes = `-- name: ListUserNotes :many
SELECT id, user_id, content_type, content_id, body, created_at, updated_at FROM notes WHERE user_id = $1 ORDER BY created_at DESC, id
`

func (q *Queries) ListUserNotes(ctx context.Context, userID pgtype.UUID) ([]Note, error) {
	rows, err := q.db.Query(ctx, listUserNotes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ContentType,
			&i.ContentID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes SET body = $1
WHERE id = $2 AND user_id = $3
RETURNING id, user_id, content_type, content_id, body, created_at, updated_at
`

type UpdateNoteParams struct {
	Body   string      `json:"body"`
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// Owner-scoped: a non-owner (or missing id) matches no row.
func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, updateNote, arg.Body, arg.ID, arg.UserID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContentType,
		&i.ContentID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
