// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: problems.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProblems = `-- name: CountProblems :one
SELECT count(*) FROM problems
WHERE ($1::difficulty IS NULL OR difficulty = $1)
  AND ($2::locale     IS NULL OR language = $2)
  AND ($3::text            IS NULL OR $3 = ANY(tags))
`

type CountProblemsParams struct {
	Difficulty NullDifficulty `json:"difficulty"`
	Language   NullLocale     `json:"language"`
	Tag        pgtype.Text    `json:"tag"`
}

func (q *Queries) CountProblems(ctx context.Context, arg CountProblemsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProblems, arg.Difficulty, arg.Language, arg.Tag)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getProblemBySlug = `-- name: GetProblemBySlug :one
SELECT id, title, slug, statement_markdown, difficulty, reference_solution_markdown, sample_io, tags, language, created_at, updated_at FROM problems WHERE slug = $1
`

func (q *Queries) GetProblemBySlug(ctx context.Context, slug string) (Problem, error) {
	row := q.db.QueryRow(ctx, getProblemBySlug, slug)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.StatementMarkdown,
		&i.Difficulty,
		&i.ReferenceSolutionMarkdown,
		&i.SampleIo,
		&i.Tags,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProblems = `-- name: ListProblems :many
SELECT id, title, slug, statement_markdown, difficulty, reference_solution_markdown, sample_io, tags, language, created_at, updated_at FROM problems
WHERE ($1::difficulty IS NULL OR difficulty = $1)
  AND ($2::locale     IS NULL OR language = $2)
  AND ($3::text            IS NULL OR $3 = ANY(tags))
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListProblemsParams struct {
	Difficulty NullDifficulty `json:"difficulty"`
	Language   NullLocale     `json:"language"`
	Tag        pgtype.Text    `json:"tag"`
	Off        int32          `json:"off"`
	Lim        int32          `json:"lim"`
}

func (q *Queries) ListProblems(ctx context.Context, arg ListProblemsParams) ([]Problem, error) {
	rows, err := q.db.Query(ctx, listProblems,
		arg.Difficulty,
		arg.Language,
		arg.Tag,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Problem{}
	for rows.Next() {
		var i Problem
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.StatementMarkdown,
			&i.Difficulty,
			&i.ReferenceSolutionMarkdown,
			&i.SampleIo,
			&i.Tags,
			&i.Language,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
