// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: problem_submissions.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProblemSubmission = `-- name: CreateProblemSubmission :one
INSERT INTO problem_submissions (user_id, problem_id, status, code, language)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, problem_id, status, code, language, verdict, created_at
`

type CreateProblemSubmissionParams struct {
	UserID    pgtype.UUID      `json:"user_id"`
	ProblemID pgtype.UUID      `json:"problem_id"`
	Status    SubmissionStatus `json:"status"`
	Code      string           `json:"code"`
	Language  string           `json:"language"`
}

func (q *Queries) CreateProblemSubmission(ctx context.Context, arg CreateProblemSubmissionParams) (ProblemSubmission, error) {
	row := q.db.QueryRow(ctx, createProblemSubmission,
		arg.UserID,
		arg.ProblemID,
		arg.Status,
		arg.Code,
		arg.Language,
	)
	var i ProblemSubmission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.Status,
		&i.Code,
		&i.Language,
		&i.Verdict,
		&i.CreatedAt,
	)
	return i, err
}

const hasSolvedProblem = `-- name: HasSolvedProblem :one
SELECT EXISTS (
    SELECT 1 FROM problem_submissions
    WHERE user_id = $1 AND problem_id = $2 AND status = 'solved'
) AS solved
`

type HasSolvedProblemParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ProblemID pgtype.UUID `json:"problem_id"`
}

func (q *Queries) HasSolvedProblem(ctx context.Context, arg HasSolvedProblemParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasSolvedProblem, arg.UserID, arg.ProblemID)
	var solved bool
	err := row.Scan(&solved)
	return solved, err
}
