// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quiz_attempts.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createQuizAttempt = `-- name: CreateQuizAttempt :one
INSERT INTO quiz_attempts (user_id, quiz_id, score, passed, answers)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, quiz_id, score, passed, answers, created_at
`

type CreateQuizAttemptParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	QuizID  pgtype.UUID `json:"quiz_id"`
	Score   int32       `json:"score"`
	Passed  bool        `json:"passed"`
	Answers []byte      `json:"answers"`
}

func (q *Queries) CreateQuizAttempt(ctx context.Context, arg CreateQuizAttemptParams) (QuizAttempt, error) {
	row := q.db.QueryRow(ctx, createQuizAttempt,
		arg.UserID,
		arg.QuizID,
		arg.Score,
		arg.Passed,
		arg.Answers,
	)
	var i QuizAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuizID,
		&i.Score,
		&i.Passed,
		&i.Answers,
		&i.CreatedAt,
	)
	return i, err
}
