// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quizzes.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countQuizzes = `-- name: CountQuizzes :one
SELECT count(*) FROM quizzes
WHERE ($1::difficulty IS NULL OR difficulty = $1)
  AND ($2::locale     IS NULL OR language = $2)
  AND ($3::text            IS NULL OR $3 = ANY(tags))
  AND ($4::text              IS NULL OR title ILIKE '%' || $4 || '%')
`

type CountQuizzesParams struct {
	Difficulty NullDifficulty `json:"difficulty"`
	Language   NullLocale     `json:"language"`
	Tag        pgtype.Text    `json:"tag"`
	Q          pgtype.Text    `json:"q"`
}

func (q *Queries) CountQuizzes(ctx context.Context, arg CountQuizzesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countQuizzes,
		arg.Difficulty,
		arg.Language,
		arg.Tag,
		arg.Q,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getQuizByID = `-- name: GetQuizByID :one
SELECT id, title, description, pass_threshold, difficulty, tags, language, created_at, updated_at FROM quizzes WHERE id = $1
`

func (q *Queries) GetQuizByID(ctx context.Context, id pgtype.UUID) (Quiz, error) {
	row := q.db.QueryRow(ctx, getQuizByID, id)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.PassThreshold,
		&i.Difficulty,
		&i.Tags,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listQuizOptionsByQuiz = `-- name: ListQuizOptionsByQuiz :many
SELECT o.id, o.question_id, o.text, o.is_correct, o.position FROM quiz_options o
JOIN quiz_questions q ON q.id = o.question_id
WHERE q.quiz_id = $1
ORDER BY q.position, o.position, o.id
`

func (q *Queries) ListQuizOptionsByQuiz(ctx context.Context, quizID pgtype.UUID) ([]QuizOption, error) {
	rows, err := q.db.Query(ctx, listQuizOptionsByQuiz, quizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuizOption{}
	for rows.Next() {
		var i QuizOption
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Text,
			&i.IsCorrect,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuizQuestions = `-- name: ListQuizQuestions :many
SELECT id, quiz_id, prompt, type, position FROM quiz_questions WHERE quiz_id = $1 ORDER BY position, id
`

func (q *Queries) ListQuizQuestions(ctx context.Context, quizID pgtype.UUID) ([]QuizQuestion, error) {
	rows, err := q.db.Query(ctx, listQuizQuestions, quizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuizQuestion{}
	for rows.Next() {
		var i QuizQuestion
		if err := rows.Scan(
			&i.ID,
			&i.QuizID,
			&i.Prompt,
			&i.Type,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuizzes = `-- name: ListQuizzes :many
SELECT id, title, description, pass_threshold, difficulty, tags, language, created_at, updated_at FROM quizzes
WHERE ($1::difficulty IS NULL OR difficulty = $1)
  AND ($2::locale     IS NULL OR language = $2)
  AND ($3::text            IS NULL OR $3 = ANY(tags))
  AND ($4::text              IS NULL OR title ILIKE '%' || $4 || '%')
ORDER BY created_at DESC
LIMIT $6 OFFSET $5
`

type ListQuizzesParams struct {
	Difficulty NullDifficulty `json:"difficulty"`
	Language   NullLocale     `json:"language"`
	Tag        pgtype.Text    `json:"tag"`
	Q          pgtype.Text    `json:"q"`
	Off        int32          `json:"off"`
	Lim        int32          `json:"lim"`
}

func (q *Queries) ListQuizzes(ctx context.Context, arg ListQuizzesParams) ([]Quiz, error) {
	rows, err := q.db.Query(ctx, listQuizzes,
		arg.Difficulty,
		arg.Language,
		arg.Tag,
		arg.Q,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Quiz{}
	for rows.Next() {
		var i Quiz
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.PassThreshold,
			&i.Difficulty,
			&i.Tags,
			&i.Language,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
