// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recent.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listRecentCompletions = `-- name: ListRecentCompletions :many
SELECT content_type, content_id, title, completed_at
FROM (
    SELECT 'video'::text AS content_type, v.id AS content_id, v.title AS title,
           vp.updated_at AS completed_at
    FROM video_progress vp
    JOIN videos v ON v.id = vp.video_id
    WHERE vp.user_id = $1 AND vp.completed

    UNION ALL

    SELECT 'article', a.id, a.title, ar.completed_at
    FROM article_reads ar
    JOIN articles a ON a.id = ar.article_id
    WHERE ar.user_id = $1

    UNION ALL

    SELECT 'quiz', q.id, q.title, max(qa.created_at)
    FROM quiz_attempts qa
    JOIN quizzes q ON q.id = qa.quiz_id
    WHERE qa.user_id = $1 AND qa.passed
    GROUP BY q.id, q.title

    UNION ALL

    SELECT 'problem', p.id, p.title, max(ps.created_at)
    FROM problem_submissions ps
    JOIN problems p ON p.id = ps.problem_id
    WHERE ps.user_id = $1 AND ps.status = 'solved'
    GROUP BY p.id, p.title
) c
ORDER BY completed_at DESC
LIMIT $2
`

type ListRecentCompletionsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

type ListRecentCompletionsRow struct {
	ContentType string             `json:"content_type"`
	ContentID   pgtype.UUID        `json:"content_id"`
	Title       string             `json:"title"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

// A unified, most-recent-first feed of content the user has finished: videos
// watched, articles read, quizzes passed and problems solved, with titles.
func (q *Queries) ListRecentCompletions(ctx context.Context, arg ListRecentCompletionsParams) ([]ListRecentCompletionsRow, error) {
	rows, err := q.db.Query(ctx, listRecentCompletions, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentCompletionsRow{}
	for rows.Next() {
		var i ListRecentCompletionsRow
		if err := rows.Scan(
			&i.ContentType,
			&i.ContentID,
			&i.Title,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
