// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_sessions.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshSession = `-- name: CreateRefreshSession :one
INSERT INTO refresh_sessions (user_id, family_id, token_hash, user_agent, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, family_id, token_hash, user_agent, expires_at, revoked_at, created_at
`

type CreateRefreshSessionParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	FamilyID  pgtype.UUID        `json:"family_id"`
	TokenHash string             `json:"token_hash"`
	UserAgent string             `json:"user_agent"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshSession(ctx context.Context, arg CreateRefreshSessionParams) (RefreshSession, error) {
	row := q.db.QueryRow(ctx, createRefreshSession,
		arg.UserID,
		arg.FamilyID,
		arg.TokenHash,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i RefreshSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.TokenHash,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshSessionByTokenHash = `-- name: GetRefreshSessionByTokenHash :one
SELECT id, user_id, family_id, token_hash, user_agent, expires_at, revoked_at, created_at FROM refresh_sessions WHERE token_hash = $1
`

func (q *Queries) GetRefreshSessionByTokenHash(ctx context.Context, tokenHash string) (RefreshSession, error) {
	row := q.db.QueryRow(ctx, getRefreshSessionByTokenHash, tokenHash)
	var i RefreshSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.TokenHash,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAllUserRefreshSessions = `-- name: RevokeAllUserRefreshSessions :exec
UPDATE refresh_sessions SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserRefreshSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserRefreshSessions, userID)
	return err
}

const revokeRefreshFamily = `-- name: RevokeRefreshFamily :exec
UPDATE refresh_sessions SET revoked_at = now() WHERE family_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshFamily(ctx context.Context, familyID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshFamily, familyID)
	return err
}

const revokeRefreshSession = `-- name: RevokeRefreshSession :exec
UPDATE refresh_sessions SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshSession, id)
	return err
}
