// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: track_enrollments.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const enrollTrack = `-- name: EnrollTrack :exec
INSERT INTO track_enrollments (user_id, track_id)
VALUES ($1, $2)
ON CONFLICT (user_id, track_id) DO NOTHING
`

type EnrollTrackParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	TrackID pgtype.UUID `json:"track_id"`
}

func (q *Queries) EnrollTrack(ctx context.Context, arg EnrollTrackParams) error {
	_, err := q.db.Exec(ctx, enrollTrack, arg.UserID, arg.TrackID)
	return err
}

const isTrackEnrolled = `-- name: IsTrackEnrolled :one
SELECT EXISTS (
    SELECT 1 FROM track_enrollments WHERE user_id = $1 AND track_id = $2
)
`

type IsTrackEnrolledParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	TrackID pgtype.UUID `json:"track_id"`
}

func (q *Queries) IsTrackEnrolled(ctx context.Context, arg IsTrackEnrolledParams) (bool, error) {
	row := q.db.QueryRow(ctx, isTrackEnrolled, arg.UserID, arg.TrackID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listEnrolledTracks = `-- name: ListEnrolledTracks :many
SELECT t.id, t.title, t.description, t.level, t.position, t.language, t.created_at, t.updated_at FROM tracks t
JOIN track_enrollments e ON e.track_id = t.id
WHERE e.user_id = $1
ORDER BY e.created_at DESC
`

func (q *Queries) ListEnrolledTracks(ctx context.Context, userID pgtype.UUID) ([]Track, error) {
	rows, err := q.db.Query(ctx, listEnrolledTracks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Track{}
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Level,
			&i.Position,
			&i.Language,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unenrollTrack = `-- name: UnenrollTrack :execrows
DELETE FROM track_enrollments WHERE user_id = $1 AND track_id = $2
`

type UnenrollTrackParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	TrackID pgtype.UUID `json:"track_id"`
}

func (q *Queries) UnenrollTrack(ctx context.Context, arg UnenrollTrackParams) (int64, error) {
	result, err := q.db.Exec(ctx, unenrollTrack, arg.UserID, arg.TrackID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
