// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tracks.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTracks = `-- name: CountTracks :one
SELECT count(*) FROM tracks
WHERE ($1::difficulty IS NULL OR level = $1)
  AND ($2::locale  IS NULL OR language = $2)
  AND ($3::text           IS NULL OR title ILIKE '%' || $3 || '%')
`

type CountTracksParams struct {
	Level    NullDifficulty `json:"level"`
	Language NullLocale     `json:"language"`
	Q        pgtype.Text    `json:"q"`
}

func (q *Queries) CountTracks(ctx context.Context, arg CountTracksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTracks, arg.Level, arg.Language, arg.Q)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTrackByID = `-- name: GetTrackByID :one
SELECT id, title, description, level, position, language, created_at, updated_at FROM tracks WHERE id = $1
`

func (q *Queries) GetTrackByID(ctx context.Context, id pgtype.UUID) (Track, error) {
	row := q.db.QueryRow(ctx, getTrackByID, id)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Level,
		&i.Position,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTrackItems = `-- name: ListTrackItems :many
SELECT id, track_id, content_type, content_id, position FROM track_items WHERE track_id = $1 ORDER BY position, id
`

func (q *Queries) ListTrackItems(ctx context.Context, trackID pgtype.UUID) ([]TrackItem, error) {
	rows, err := q.db.Query(ctx, listTrackItems, trackID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrackItem{}
	for rows.Next() {
		var i TrackItem
		if err := rows.Scan(
			&i.ID,
			&i.TrackID,
			&i.ContentType,
			&i.ContentID,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracks = `-- name: ListTracks :many
SELECT id, title, description, level, position, language, created_at, updated_at FROM tracks
WHERE ($1::difficulty IS NULL OR level = $1)
  AND ($2::locale  IS NULL OR language = $2)
  AND ($3::text           IS NULL OR title ILIKE '%' || $3 || '%')
ORDER BY position, created_at DESC
LIMIT $5 OFFSET $4
`

type ListTracksParams struct {
	Level    NullDifficulty `json:"level"`
	Language NullLocale     `json:"language"`
	Q        pgtype.Text    `json:"q"`
	Off      int32          `json:"off"`
	Lim      int32          `json:"lim"`
}

func (q *Queries) ListTracks(ctx context.Context, arg ListTracksParams) ([]Track, error) {
	rows, err := q.db.Query(ctx, listTracks,
		arg.Level,
		arg.Language,
		arg.Q,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Track{}
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Level,
			&i.Position,
			&i.Language,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
