// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: track_progress.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completedVideoIDs = `-- name: CompletedVideoIDs :many
SELECT video_id FROM video_progress
WHERE user_id = $1 AND completed = true
  AND video_id = ANY($2::uuid[])
`

type CompletedVideoIDsParams struct {
	UserID pgtype.UUID   `json:"user_id"`
	Ids    []pgtype.UUID `json:"ids"`
}

func (q *Queries) CompletedVideoIDs(ctx context.Context, arg CompletedVideoIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, completedVideoIDs, arg.UserID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var video_id pgtype.UUID
		if err := rows.Scan(&video_id); err != nil {
			return nil, err
		}
		items = append(items, video_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const passedQuizIDs = `-- name: PassedQuizIDs :many
SELECT DISTINCT quiz_id FROM quiz_attempts
WHERE user_id = $1 AND passed = true
  AND quiz_id = ANY($2::uuid[])
`

type PassedQuizIDsParams struct {
	UserID pgtype.UUID   `json:"user_id"`
	Ids    []pgtype.UUID `json:"ids"`
}

func (q *Queries) PassedQuizIDs(ctx context.Context, arg PassedQuizIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, passedQuizIDs, arg.UserID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var quiz_id pgtype.UUID
		if err := rows.Scan(&quiz_id); err != nil {
			return nil, err
		}
		items = append(items, quiz_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readArticleIDs = `-- name: ReadArticleIDs :many
SELECT article_id FROM article_reads
WHERE user_id = $1
  AND article_id = ANY($2::uuid[])
`

type ReadArticleIDsParams struct {
	UserID pgtype.UUID   `json:"user_id"`
	Ids    []pgtype.UUID `json:"ids"`
}

func (q *Queries) ReadArticleIDs(ctx context.Context, arg ReadArticleIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, readArticleIDs, arg.UserID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var article_id pgtype.UUID
		if err := rows.Scan(&article_id); err != nil {
			return nil, err
		}
		items = append(items, article_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const solvedProblemIDs = `-- name: SolvedProblemIDs :many
SELECT DISTINCT problem_id FROM problem_submissions
WHERE user_id = $1 AND status = 'solved'
  AND problem_id = ANY($2::uuid[])
`

type SolvedProblemIDsParams struct {
	UserID pgtype.UUID   `json:"user_id"`
	Ids    []pgtype.UUID `json:"ids"`
}

func (q *Queries) SolvedProblemIDs(ctx context.Context, arg SolvedProblemIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, solvedProblemIDs, arg.UserID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var problem_id pgtype.UUID
		if err := rows.Scan(&problem_id); err != nil {
			return nil, err
		}
		items = append(items, problem_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
