// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, display_name, locale)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, email_verified, role, is_blocked, display_name, avatar_url, bio, location, locale, is_public, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	DisplayName  string `json:"display_name"`
	Locale       Locale `json:"locale"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Locale,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.Role,
		&i.IsBlocked,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Location,
		&i.Locale,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, email_verified, role, is_blocked, display_name, avatar_url, bio, location, locale, is_public, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.Role,
		&i.IsBlocked,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Location,
		&i.Locale,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, email_verified, role, is_blocked, display_name, avatar_url, bio, location, locale, is_public, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.Role,
		&i.IsBlocked,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Location,
		&i.Locale,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setEmailVerified = `-- name: SetEmailVerified :exec
UPDATE users SET email_verified = true WHERE id = $1
`

func (q *Queries) SetEmailVerified(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setEmailVerified, id)
	return err
}

const updateAvatarURL = `-- name: UpdateAvatarURL :one
UPDATE users SET avatar_url = $1 WHERE id = $2 RETURNING id, email, password_hash, email_verified, role, is_blocked, display_name, avatar_url, bio, location, locale, is_public, created_at, updated_at
`

type UpdateAvatarURLParams struct {
	AvatarUrl pgtype.Text `json:"avatar_url"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateAvatarURL(ctx context.Context, arg UpdateAvatarURLParams) (User, error) {
	row := q.db.QueryRow(ctx, updateAvatarURL, arg.AvatarUrl, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.Role,
		&i.IsBlocked,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Location,
		&i.Locale,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE users SET password_hash = $1 WHERE id = $2
`

type UpdatePasswordHashParams struct {
	PasswordHash string      `json:"password_hash"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.Exec(ctx, updatePasswordHash, arg.PasswordHash, arg.ID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users SET
    display_name = COALESCE($1, display_name),
    bio          = COALESCE($2, bio),
    location     = COALESCE($3, location),
    locale       = COALESCE($4, locale),
    is_public    = COALESCE($5, is_public)
WHERE id = $6
RETURNING id, email, password_hash, email_verified, role, is_blocked, display_name, avatar_url, bio, location, locale, is_public, created_at, updated_at
`

type UpdateUserProfileParams struct {
	DisplayName pgtype.Text `json:"display_name"`
	Bio         pgtype.Text `json:"bio"`
	Location    pgtype.Text `json:"location"`
	Locale      NullLocale  `json:"locale"`
	IsPublic    pgtype.Bool `json:"is_public"`
	ID          pgtype.UUID `json:"id"`
}

// Partial update: a NULL argument leaves the existing column value unchanged.
func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.DisplayName,
		arg.Bio,
		arg.Location,
		arg.Locale,
		arg.IsPublic,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.Role,
		&i.IsBlocked,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Location,
		&i.Locale,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
