// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_stats.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activityExists = `-- name: ActivityExists :one
SELECT EXISTS(
    SELECT 1 FROM activity_log
    WHERE user_id = $1
      AND activity_type = $2
      AND ref_id = $3
)
`

type ActivityExistsParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	ActivityType string      `json:"activity_type"`
	RefID        pgtype.UUID `json:"ref_id"`
}

// True if the user already has an activity of this type for this referenced
// entity (used to award XP only on the first occurrence).
func (q *Queries) ActivityExists(ctx context.Context, arg ActivityExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, activityExists, arg.UserID, arg.ActivityType, arg.RefID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const ensureUserStats = `-- name: EnsureUserStats :exec
INSERT INTO user_stats (user_id) VALUES ($1) ON CONFLICT (user_id) DO NOTHING
`

// Guarantees a stats row exists (defaults) so it can then be locked and updated.
func (q *Queries) EnsureUserStats(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, ensureUserStats, userID)
	return err
}

const getUserStats = `-- name: GetUserStats :one
SELECT user_id, total_xp, level, current_streak, longest_streak, last_active_date, updated_at FROM user_stats WHERE user_id = $1
`

func (q *Queries) GetUserStats(ctx context.Context, userID pgtype.UUID) (UserStat, error) {
	row := q.db.QueryRow(ctx, getUserStats, userID)
	var i UserStat
	err := row.Scan(
		&i.UserID,
		&i.TotalXp,
		&i.Level,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastActiveDate,
		&i.UpdatedAt,
	)
	return i, err
}

const lockUserStats = `-- name: LockUserStats :one
SELECT user_id, total_xp, level, current_streak, longest_streak, last_active_date, updated_at FROM user_stats WHERE user_id = $1 FOR UPDATE
`

// Row-locks the user's stats for the rest of the transaction, serializing
// concurrent XP/streak updates (no lost updates).
func (q *Queries) LockUserStats(ctx context.Context, userID pgtype.UUID) (UserStat, error) {
	row := q.db.QueryRow(ctx, lockUserStats, userID)
	var i UserStat
	err := row.Scan(
		&i.UserID,
		&i.TotalXp,
		&i.Level,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastActiveDate,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserStats = `-- name: UpdateUserStats :exec
UPDATE user_stats SET
    total_xp         = $1,
    level            = $2,
    current_streak   = $3,
    longest_streak   = $4,
    last_active_date = $5
WHERE user_id = $6
`

type UpdateUserStatsParams struct {
	TotalXp        int32       `json:"total_xp"`
	Level          int32       `json:"level"`
	CurrentStreak  int32       `json:"current_streak"`
	LongestStreak  int32       `json:"longest_streak"`
	LastActiveDate pgtype.Date `json:"last_active_date"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateUserStats(ctx context.Context, arg UpdateUserStatsParams) error {
	_, err := q.db.Exec(ctx, updateUserStats,
		arg.TotalXp,
		arg.Level,
		arg.CurrentStreak,
		arg.LongestStreak,
		arg.LastActiveDate,
		arg.UserID,
	)
	return err
}
