// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: videos.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countVideos = `-- name: CountVideos :one
SELECT count(*) FROM videos
WHERE ($1::difficulty IS NULL OR difficulty = $1)
  AND ($2::locale     IS NULL OR language = $2)
  AND ($3::text            IS NULL OR $3 = ANY(tags))
  AND ($4::text              IS NULL OR title ILIKE '%' || $4 || '%')
  AND ($5::bool OR NOT ('hidden' = ANY(tags)))
`

type CountVideosParams struct {
	Difficulty NullDifficulty `json:"difficulty"`
	Language   NullLocale     `json:"language"`
	Tag        pgtype.Text    `json:"tag"`
	Q          pgtype.Text    `json:"q"`
	ShowHidden bool           `json:"show_hidden"`
}

func (q *Queries) CountVideos(ctx context.Context, arg CountVideosParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVideos,
		arg.Difficulty,
		arg.Language,
		arg.Tag,
		arg.Q,
		arg.ShowHidden,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getVideoByID = `-- name: GetVideoByID :one
SELECT id, title, description, youtube_id, duration_seconds, difficulty, tags, language, created_at, updated_at FROM videos WHERE id = $1
`

func (q *Queries) GetVideoByID(ctx context.Context, id pgtype.UUID) (Video, error) {
	row := q.db.QueryRow(ctx, getVideoByID, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.YoutubeID,
		&i.DurationSeconds,
		&i.Difficulty,
		&i.Tags,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVideos = `-- name: ListVideos :many
SELECT id, title, description, youtube_id, duration_seconds, difficulty, tags, language, created_at, updated_at FROM videos
WHERE ($1::difficulty IS NULL OR difficulty = $1)
  AND ($2::locale     IS NULL OR language = $2)
  AND ($3::text            IS NULL OR $3 = ANY(tags))
  AND ($4::text              IS NULL OR title ILIKE '%' || $4 || '%')
  AND ($5::bool OR NOT ('hidden' = ANY(tags)))
ORDER BY created_at DESC
LIMIT $7 OFFSET $6
`

type ListVideosParams struct {
	Difficulty NullDifficulty `json:"difficulty"`
	Language   NullLocale     `json:"language"`
	Tag        pgtype.Text    `json:"tag"`
	Q          pgtype.Text    `json:"q"`
	ShowHidden bool           `json:"show_hidden"`
	Off        int32          `json:"off"`
	Lim        int32          `json:"lim"`
}

func (q *Queries) ListVideos(ctx context.Context, arg ListVideosParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, listVideos,
		arg.Difficulty,
		arg.Language,
		arg.Tag,
		arg.Q,
		arg.ShowHidden,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.YoutubeID,
			&i.DurationSeconds,
			&i.Difficulty,
			&i.Tags,
			&i.Language,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
