// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: video_progress.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getVideoProgress = `-- name: GetVideoProgress :one
SELECT user_id, video_id, watched_percent, last_position_seconds, completed, updated_at FROM video_progress WHERE user_id = $1 AND video_id = $2
`

type GetVideoProgressParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	VideoID pgtype.UUID `json:"video_id"`
}

func (q *Queries) GetVideoProgress(ctx context.Context, arg GetVideoProgressParams) (VideoProgress, error) {
	row := q.db.QueryRow(ctx, getVideoProgress, arg.UserID, arg.VideoID)
	var i VideoProgress
	err := row.Scan(
		&i.UserID,
		&i.VideoID,
		&i.WatchedPercent,
		&i.LastPositionSeconds,
		&i.Completed,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertVideoProgress = `-- name: UpsertVideoProgress :one
INSERT INTO video_progress (user_id, video_id, watched_percent, last_position_seconds, completed)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, video_id) DO UPDATE SET
    watched_percent       = GREATEST(video_progress.watched_percent, EXCLUDED.watched_percent),
    last_position_seconds = EXCLUDED.last_position_seconds,
    completed             = video_progress.completed OR EXCLUDED.completed
RETURNING user_id, video_id, watched_percent, last_position_seconds, completed, updated_at
`

type UpsertVideoProgressParams struct {
	UserID              pgtype.UUID `json:"user_id"`
	VideoID             pgtype.UUID `json:"video_id"`
	WatchedPercent      int32       `json:"watched_percent"`
	LastPositionSeconds int32       `json:"last_position_seconds"`
	Completed           bool        `json:"completed"`
}

// watched_percent never decreases; completed is sticky (once true, stays true).
func (q *Queries) UpsertVideoProgress(ctx context.Context, arg UpsertVideoProgressParams) (VideoProgress, error) {
	row := q.db.QueryRow(ctx, upsertVideoProgress,
		arg.UserID,
		arg.VideoID,
		arg.WatchedPercent,
		arg.LastPositionSeconds,
		arg.Completed,
	)
	var i VideoProgress
	err := row.Scan(
		&i.UserID,
		&i.VideoID,
		&i.WatchedPercent,
		&i.LastPositionSeconds,
		&i.Completed,
		&i.UpdatedAt,
	)
	return i, err
}
